/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/CoreDuetDaemonProtocol
 */

@class NSString, CDDXPCConnection, CDDebug;

@interface CDPClientConnection : NSObject  {
    bool_admissionOverride;
    bool_admissionResult;
    NSString *_clientName;
    CDDXPCConnection *_connection;
    CDDebug *_debug;
}

@property(readonly) NSString * clientName;
@property bool admissionOverride;
@property bool admissionResult;
@property(readonly) CDDXPCConnection * connection;
@property(readonly) CDDebug * debug;


- (id)clientName;
- (void)setAdmissionResult:(bool)arg1;
- (bool)admissionResult;
- (void)setAdmissionOverride:(bool)arg1;
- (bool)admissionOverride;
- (bool)admissionCheckAndStartedForAttributes:(id)arg1 admissionId:(id)arg2 options:(id)arg3 error:(id*)arg4 replyHandler:(id)arg5;
- (bool)activitySignal:(id)arg1 error:(id*)arg2 replyHandler:(id)arg3;
- (bool)admissionSignoffForAttributes:(id)arg1 admissionId:(id)arg2 options:(id)arg3 error:(id*)arg4 replyHandler:(id)arg5;
- (bool)triggerWithConditions:(id)arg1 error:(id*)arg2 replyHandler:(id)arg3;
- (bool)bootstrapWithError:(id*)arg1 replyHandler:(id)arg2;
- (id)initWithPluginName:(id)arg1 error:(id*)arg2;
- (bool)sendMessage:(long long)arg1 withXPCdictionaryKey:(id)arg2 dictionary:(id)arg3 admissionId:(id)arg4 options:(id)arg5 error:(id*)arg6 replyHandler:(id)arg7;
- (id)messageWithError:(id*)arg1;
- (id)connection;
- (void).cxx_destruct;
- (id)init;
- (id)debug;

@end
