/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@class NSUUID, NSDictionary, NSString, NSDate;

@interface LSBestAppSuggestion : NSObject  {
    unsigned long long _type;
    NSUUID *_uniqueIdentifier;
    NSDictionary *_options;
    NSString *_bundleIdentifier;
    NSString *_activityType;
    NSDate *_lastUpdateTime;
    double _confidence;
    NSString *_originatingDeviceIdentifier;
    NSString *_originatingDeviceName;
    NSString *_originatingDeviceType;
}

@property(copy,readonly) NSString * userActivityTypeIdentifier;
@property(readonly) unsigned long long type;
@property(copy) NSUUID * uniqueIdentifier;
@property(copy,readonly) NSString * bundleIdentifier;
@property(copy) NSString * activityType;
@property(copy,readonly) NSDate * lastUpdateTime;
@property(copy,readonly) NSDate * when;
@property(copy,readonly) NSDictionary * options;
@property(readonly) double confidence;
@property(copy,readonly) NSString * originatingDeviceIdentifier;
@property(copy,readonly) NSString * originatingDeviceName;
@property(copy,readonly) NSString * originatingDeviceType;

+ (bool)supportsSecureCoding;

- (void)setActivityType:(id)arg1;
- (id)lastUpdateTime;
- (id)originatingDeviceName;
- (id)originatingDeviceType;
- (void)setUniqueIdentifier:(id)arg1;
- (id)uniqueIdentifier;
- (id)activityType;
- (id)options;
- (unsigned long long)type;
- (id)bundleIdentifier;
- (id)debugDescription;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)originatingDeviceIdentifier;
- (id)when;
- (id)initWithBundleIdentifier:(id)arg1 uuid:(id)arg2 activityType:(id)arg3 lastUpdateTime:(id)arg4 type:(unsigned long long)arg5 deviceName:(id)arg6 deviceIdentifier:(id)arg7 deviceType:(id)arg8 options:(id)arg9;
- (double)confidence;
- (id)userActivityTypeIdentifier;

@end
