/* Generated by RuntimeBrowser.
   Image: /usr/lib/system/libdispatch.dylib
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@interface OS_dispatch_data : _NSDispatchData <OS_dispatch_data> {
}

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (bool)_bytesAreVM;
- (void)_setFinalizer:(int (*)())arg1;
- (void*)_getContext;
- (void)finalize;
- (void)_setTargetQueue:(id)arg1;
- (void)_setContext:(void*)arg1;
- (id)debugDescription;
- (id)init;
- (void)dealloc;
- (id)initWithBytes:(void*)arg1 length:(unsigned long long)arg2 copy:(bool)arg3 freeWhenDone:(bool)arg4 bytesAreVM:(bool)arg5;

@end
