/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
 */

@interface PLSandboxedURL : NSURL  {
    long long _sandboxExtensionHandle;
}


- (id)initWithURL:(id)arg1 sandboxExtensionToken:(id)arg2;
- (void)dealloc;

@end
