/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
 */

@interface PLSecurity : NSObject  {
}

+ (bool)connection:(id)arg1 hasEntitlement:(id)arg2;
+ (bool)secTask:(struct __SecTask { }*)arg1 hasEntitlement:(id)arg2;
+ (bool)isEntitledForPhotoKit;
+ (bool)connectionIsEntitledForPhotoKit:(id)arg1;


@end
