/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSLogger : NSObject  {
}

+ (bool)isEnabled;
+ (id)environment;


@end
