/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@class BSMutableSettings;

@interface FBSSceneSettingsDiffInspector : NSObject  {
    BSMutableSettings *_observerInfo;
    bool_iteratingObservers;
}


- (void)observeIsBackgroundedWithBlock:(id)arg1;
- (void)observeInterfaceOrientationWithBlock:(id)arg1;
- (void)observeLevelWithBlock:(id)arg1;
- (void)observeFrameWithBlock:(id)arg1;
- (void)observeClassWithBlock:(id)arg1;
- (void)removeAllObservers;
- (void)_addObserver:(id)arg1 forSetting:(unsigned long long)arg2 inInfo:(id)arg3;
- (void)observeOcclusionsWithBlock:(id)arg1;
- (void)observeOtherSetting:(unsigned long long)arg1 withBlock:(id)arg2;
- (void)inspectDiff:(id)arg1 withContext:(void*)arg2;
- (id)description;
- (id)init;
- (void)dealloc;

@end
