/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@class NSString, <FBSUIApplicationWorkspaceDelegate>;

@interface FBSUIApplicationWorkspace : FBSWorkspace <FBSUIApplicationWorkspaceClientDelegate> {
}

@property <FBSUIApplicationWorkspaceDelegate> * delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (bool)isUIApplicationWorkspace;
- (Class)_clientClass;
- (void)clientHandleAssertionExpirationImminent:(id)arg1;
- (void)clientHandleExit:(id)arg1;
- (void)client:(id)arg1 handleLaunch:(id)arg2 withCompletion:(id)arg3;

@end
