/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@class NSObject<OS_dispatch_queue>, NSString, <FBSUIApplicationSystemServiceDelegate>;

@interface FBSUIApplicationSystemService : NSObject  {
    NSObject<OS_dispatch_queue> *_delegateQueue;
    <FBSUIApplicationSystemServiceDelegate> *_delegate;
}

@property <FBSUIApplicationSystemServiceDelegate> * delegate;
@property long long badgeNumber;
@property(copy) NSString * badgeString;
@property(readonly) double backgroundTimeRemaining;
@property double currentBacklightLevel;


- (id)badgeString;
- (id)_getBadgeValue;
- (double)currentBacklightLevel;
- (void)setCurrentBacklightLevel:(double)arg1;
- (bool)setNextWakeInterval:(double)arg1;
- (double)backgroundTimeRemaining;
- (void)setBadgeNumber:(long long)arg1;
- (long long)badgeNumber;
- (void)setBadgeString:(id)arg1;
- (id)initWithQueue:(id)arg1;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end
