/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@class NSSet;

@interface FBSWorkspaceSceneActionsEvent : FBSWorkspaceSceneEvent  {
    NSSet *_actions;
}

@property(copy) NSSet * actions;


- (void)setActions:(id)arg1;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (id)actions;
- (void)dealloc;

@end
