/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@class FBSWorkspaceSceneUpdateResponse;

@interface FBSWorkspaceSceneUpdateResponseEvent : FBSWorkspaceSceneEvent  {
    FBSWorkspaceSceneUpdateResponse *_response;
}

@property(retain) FBSWorkspaceSceneUpdateResponse * response;


- (void)setResponse:(id)arg1;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (id)response;
- (void)dealloc;

@end
