/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSDictionary, NSMutableString;

@interface __NSLocalizedString : NSMutableString  {
    NSMutableString *original;
    NSDictionary *config;
}


- (long long)compare:(id)arg1 options:(unsigned long long)arg2 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3 locale:(id)arg4;
- (void)getCharacters:(unsigned short*)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (void)setString:(id)arg1;
- (void)replaceCharactersInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 withString:(id)arg2;
- (unsigned long long)replaceOccurrencesOfString:(id)arg1 withString:(id)arg2 options:(unsigned long long)arg3 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg4;
- (id)substringToIndex:(unsigned long long)arg1;
- (unsigned short)characterAtIndex:(unsigned long long)arg1;
- (void)deleteCharactersInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)substringWithRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)appendFormat:(id)arg1;
- (void)appendString:(id)arg1;
- (unsigned long long)length;
- (id)substringFromIndex:(unsigned long long)arg1;
- (void)dealloc;
- (bool)isEqualToString:(id)arg1;
- (id)baseString;
- (id)initWithString:(id)arg1 withFormatConfiguration:(id)arg2;
- (id)formatConfiguration;
- (void)appendCharacters:(const unsigned short*)arg1 length:(unsigned long long)arg2;
- (const unsigned short*)_fastCharacterContents;
- (const char *)_fastCStringContents:(bool)arg1;
- (void)insertString:(id)arg1 atIndex:(unsigned long long)arg2;

@end
