/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSLock;

@interface _NSXPCConnectionImportInfo : NSObject  {
    NSLock *_lock;
    struct __CFDictionary { } *_map;
}


- (void)finalize;
- (id)init;
- (void)dealloc;
- (bool)decrement:(unsigned long long)arg1;
- (void)increment:(unsigned long long)arg1;

@end
