/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSCFType : NSObject  {
}

+ (bool)automaticallyNotifiesObserversForKey:(id)arg1;

- (void)finalize;
- (oneway void)release;
- (bool)retainWeakReference;
- (bool)allowsWeakReference;
- (unsigned long long)hash;
- (unsigned long long)retainCount;
- (bool)isEqual:(id)arg1;
- (id)retain;

@end
