/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@interface NSClassicHashTable : NSHashTable  {
    struct { 
        int (*hash)(); 
        int (*isEqual)(); 
        int (*retain)(); 
        int (*release)(); 
        int (*describe)(); 
    } _callBacks;
    struct __CFBasicHash { } *_ht;
}


- (void)removeItem:(const void*)arg1;
- (id)allObjects;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)copy;
- (void)addObject:(id)arg1;
- (id)init;
- (unsigned long long)count;
- (void)dealloc;
- (void)removeAllItems;
- (void)insertItem:(const void*)arg1;
- (void)getKeys:(const void**)arg1 count:(unsigned long long*)arg2;
- (void)insertKnownAbsentItem:(const void*)arg1;
- (void*)getItem:(const void*)arg1;

@end
