/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class Protocol, NSObject;

@interface NSConcreteProtocolChecker : NSProtocolChecker  {
    NSObject *_target;
    Protocol *_protocol;
}


- (id)protocol;
- (id)target;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 protocol:(id)arg2;

@end
