/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSFileHandle;

@interface NSConcretePipe : NSPipe  {
    NSFileHandle *_readHandle;
    NSFileHandle *_writeHandle;
}


- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (void)dealloc;
- (id)fileHandleForWriting;
- (id)fileHandleForReading;

@end
