/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSISRestrictedToNonNegativeMarkerVariable : NSISVariable  {
}


- (bool)shouldBeMinimized;
- (id)markedConstraint;
- (int)valueRestriction;

@end
