/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSString;

@interface NSKeyPathSpecifierExpression : NSExpression  {
    NSString *_value;
}

+ (bool)supportsSecureCoding;

- (id)constantValue;
- (id)initWithObject:(id)arg1;
- (id)keyPath;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)predicateFormat;
- (id)expressionValueWithObject:(id)arg1 context:(id)arg2;

@end
