/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString, NSDocInfo;

@interface NSLeafProxy <NSCopying> {
    Class isa;
    NSString *dir;
    NSString *file;
    NSDocInfo *docInfo;
    long long refCount;
    id realObject;
}

+ (id)alloc;
+ (void)forwardInvocation:(id)arg1;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (/* Warning: Unrecognized filer type: '' using 'void*' */ void*)initialize;
     /* Encoded args for previous method:  */


- (void)release;
- (void)forwardInvocation:(id)arg1;
- (bool)_isDeallocating;
- (bool)_tryRetain;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (unsigned long long)retainCount;
- (bool)isProxy;
- (id)autorelease;
- (id)copy;
- (void)dealloc;
- (id)retain;
- (void)reallyDealloc;
- (id)initDir:(id)arg1 file:(id)arg2 docInfo:(id)arg3;

@end
