/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSString;

@interface NSLocalizableString : NSString  {
    NSString *_stringsFileKey;
    NSString *_developmentLanguageString;
}

@property(copy,readonly) NSString * stringsFileKey;
@property(copy,readonly) NSString * developmentLanguageString;

+ (id)localizableStringWithStringsFileKey:(id)arg1 developmentLanguageString:(id)arg2;

- (id)awakeAfterUsingCoder:(id)arg1;
- (unsigned short)characterAtIndex:(unsigned long long)arg1;
- (Class)classForCoder;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)length;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)setDevelopmentLanguageString:(id)arg1;
- (id)developmentLanguageString;
- (void)setStringsFileKey:(id)arg1;
- (id)stringsFileKey;
- (id)initWithStringsFileKey:(id)arg1 developmentLanguageString:(id)arg2;

@end
