/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSNotificationCenter : NSObject  {
    void *_impl;
    void *_callback;
    void *_pad[11];
}

+ (id)defaultCenter;

- (void)finalize;
- (void)postNotification:(id)arg1;
- (void)removeObserver:(id)arg1;
- (bool)isEmpty;
- (id)addObserverForName:(id)arg1 object:(id)arg2 queue:(id)arg3 usingBlock:(id)arg4;
- (void)postNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)postNotificationName:(id)arg1 object:(id)arg2;
- (void)removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3;
- (id)description;
- (id)init;
- (void)dealloc;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;
- (void)__mainThreadPostNotification:(id)arg1;
- (void)postNotificationName:(id)arg1;
- (void)__mainThreadPostNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)__mainThreadPostNotificationName:(id)arg1 object:(id)arg2;

@end
