/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSSelfExpression : NSExpression  {
}

+ (void)initialize;
+ (bool)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (bool)_allowsEvaluation;
+ (id)defaultInstance;

- (oneway void)release;
- (bool)_isDeallocating;
- (bool)_tryRetain;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (unsigned long long)retainCount;
- (bool)isEqual:(id)arg1;
- (id)autorelease;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)retain;
- (id)_initPrivate;
- (id)predicateFormat;
- (id)expressionValueWithObject:(id)arg1 context:(id)arg2;

@end
