/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSSimpleAttributeDictionary;

@interface NSSimpleAttributeDictionaryEnumerator : NSEnumerator  {
    NSSimpleAttributeDictionary *dictionary;
    unsigned long long nextElement;
}


- (void)finalize;
- (id)nextObject;
- (void)dealloc;
- (id)initWithAttributeDictionary:(id)arg1;

@end
