/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSData;

@interface NSSubrangeData : NSData  {
    unsigned int _reserved : 3;
    unsigned int _retainCount : 29;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    } _range;
    NSData *_data;
}


- (void)getBytes:(void*)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (void)getBytes:(void*)arg1 length:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (const void*)bytes;
- (unsigned long long)length;
- (id)init;
- (void)dealloc;
- (void)getBytes:(void*)arg1;
- (id)initWithData:(id)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (bool)_isCompact;

@end
