/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSExpression, NSVariableExpression;

@interface NSVariableAssignmentExpression : NSExpression  {
    NSVariableExpression *_assignmentVariable;
    NSExpression *_subexpression;
}

+ (bool)supportsSecureCoding;

- (id)variable;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)assignmentVariable;
- (id)initWithAssignmentExpression:(id)arg1 expression:(id)arg2;
- (id)subexpression;
- (id)initWithAssignmentVariable:(id)arg1 expression:(id)arg2;
- (id)_expressionWithSubstitutionVariables:(id)arg1;
- (id)predicateFormat;
- (id)expressionValueWithObject:(id)arg1 context:(id)arg2;
- (void)acceptVisitor:(id)arg1 flags:(unsigned long long)arg2;
- (void)allowEvaluation;

@end
