/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSXPCListenerEndpoint, NSString, <NSXPCListenerDelegate>, NSObject<OS_dispatch_queue>;

@interface NSXPCListener : NSObject  {
    void *_xconnection;
    NSObject<OS_dispatch_queue> *_userQueue;
    void *reserved0;
    <NSXPCListenerDelegate> *_delegate;
    NSString *_serviceName;
    unsigned long long _state;
    id _reserved1;
    id _reserved2;
}

@property <NSXPCListenerDelegate> * delegate;
@property(retain,readonly) NSXPCListenerEndpoint * endpoint;

+ (void)enableTransactions;
+ (id)anonymousListener;
+ (id)serviceListener;
+ (id)_UUID;

- (void)finalize;
- (id)serviceName;
- (id)_xpcConnection;
- (id)endpoint;
- (void)stop;
- (id)_queue;
- (id)initWithServiceName:(id)arg1;
- (void)_setQueue:(id)arg1;
- (void)setOptions:(unsigned long long)arg1;
- (id)initWithMachServiceName:(id)arg1;
- (void)resume;
- (void)suspend;
- (void)invalidate;
- (id)delegate;
- (id)description;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)_initShared;

@end
