/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CLCompassDatabaseClientAdapter : CLNotifierServiceAdapter <CLCompassDatabaseClientProtocol> {
}

@property bool valid;

+ (id)getSilo;
+ (void)becameFatallyBlocked:(id)arg1;

- (id)initInSilo:(id)arg1;
- (void)endService;
- (void)beginService;

@end
