/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CLDeviceMotionProperties : NSObject  {
    int fMode;
    boolfWantsPowerConservativeDeviceMotion;
}

@property int mode;
@property(readonly) bool wantsPowerConservativeDeviceMotion;


- (int)mode;
- (void)setMode:(int)arg1;
- (id)description;
- (bool)wantsPowerConservativeDeviceMotion;
- (id)initWithMode:(int)arg1 andPowerConservation:(bool)arg2;

@end
