/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@class NSNumber;

@interface CMAltitudeData : CMLogItem  {
    id _internal;
}

@property(readonly) NSNumber * relativeAltitude;
@property(readonly) NSNumber * pressure;


- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)pressure;
- (id)relativeAltitude;
- (id)initWithAltitude:(float)arg1 andTimestamp:(double)arg2 atBaseAltitude:(float)arg3;

@end
