/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class NSString, <IMConnectionMonitorDelegate>;

@interface IMConnectionMonitor : NSObject  {
    NSString *_remoteHost;
    <IMConnectionMonitorDelegate> *_delegate;
}

@property(readonly) bool isImmediatelyReachable;
@property(readonly) bool requiresDataConnectionActivation;
@property(setter=setDataConnectionActive:) bool isDataConnectionActive;
@property <IMConnectionMonitorDelegate> * delegate;
@property(readonly) NSString * remoteHost;

+ (id)alloc;

- (void)_setup;
- (id)remoteHost;
- (bool)requiresDataConnectionActivation;
- (bool)isDataConnectionActive;
- (void)setDataConnectionActive:(bool)arg1;
- (void)goDisconnected;
- (void)goConnectedWithLocalSocketAddress:(id)arg1 remoteSocketAddress:(id)arg2;
- (bool)isImmediatelyReachable;
- (id)initWithRemoteHost:(id)arg1 delegate:(id)arg2;
- (void)clear;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end
