/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class NSString, NSRecursiveLock;

@interface IMDeviceSupport : NSObject  {
    NSString *_model;
    NSString *_productName;
    NSString *_productVersion;
    NSString *_buildVersion;
    NSRecursiveLock *_lock;
}

@property(readonly) NSString * model;
@property(readonly) NSString * userAgentString;
@property(readonly) NSString * productName;
@property(readonly) NSString * productVersion;
@property(readonly) NSString * productBuildVersion;
@property(readonly) NSString * deviceInformationString;

+ (id)marketingNameForModel:(id)arg1;
+ (id)sharedInstance;

- (id)productBuildVersion;
- (id)deviceInformationString;
- (id)userAgentString;
- (void)_generateProductInformation;
- (id)productVersion;
- (id)productName;
- (id)model;
- (id)init;
- (void)dealloc;

@end
