/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class IMReachability;

@interface IMNetworkConnectionMonitor : IMConnectionMonitor <IMSystemMonitorListener, IMReachabilityDelegate> {
    bool_isConnected;
    bool_isSleeping;
    IMReachability *_hostReachability;
    IMReachability *_ipReachability;
    unsigned long long _hostFlags;
    unsigned long long _ipFlags;
}

@property(retain) IMReachability * _hostReachability;
@property(retain) IMReachability * _ipReachability;
@property unsigned long long _hostFlags;
@property unsigned long long _ipFlags;
@property bool _isConnected;
@property bool _isSleeping;


- (void)_setup;
- (void)systemWillSleep;
- (void)systemDidWake;
- (void)set_isSleeping:(bool)arg1;
- (bool)_isSleeping;
- (void)set_isConnected:(bool)arg1;
- (bool)_isConnected;
- (void)set_ipFlags:(unsigned long long)arg1;
- (unsigned long long)_ipFlags;
- (void)set_hostFlags:(unsigned long long)arg1;
- (unsigned long long)_hostFlags;
- (void)set_ipReachability:(id)arg1;
- (id)_ipReachability;
- (void)set_hostReachability:(id)arg1;
- (id)_hostReachability;
- (void)_networkManagedUpdated:(id)arg1;
- (void)_doCallbackLater;
- (void)_doCallbackNow;
- (void)_clearReachability:(id*)arg1 flags:(unsigned long long*)arg2;
- (void)goDisconnected;
- (void)goConnectedWithLocalSocketAddress:(id)arg1 remoteSocketAddress:(id)arg2;
- (void)reachabilityDidChange:(id)arg1;
- (bool)isImmediatelyReachable;
- (void)_setupReachability;
- (void)clear;
- (void)dealloc;

@end
