/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class NSMutableArray;

@interface IMWeakArray : NSObject  {
    NSMutableArray *_weakArray;
}


- (id)copyMutableSet;
- (void)addObjectIfNotIdenticalObjectExists:(id)arg1;
- (id)copyMutableArray;
- (id)description;
- (void)addObject:(id)arg1;
- (void)removeObject:(id)arg1;
- (void)dealloc;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long *x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;

@end
