/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@class CUIPSDGradient;

@interface CUIPSDGradientLayer : CUIPSDLayer  {
    CUIPSDGradient *_gradient;
}

@property(readonly) CUIPSDGradient * gradient;


- (id)initWithGradient:(id)arg1;
- (id)gradient;
- (void)dealloc;

@end
