/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@class NSArray;

@interface TUCallGroup : NSObject  {
    NSArray *_calls;
}

@property(retain) NSArray * calls;


- (void)setCalls:(id)arg1;
- (id)calls;
- (int)status;
- (id)displayName;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)description;
- (bool)isEqual:(id)arg1;
- (void)dealloc;

@end
