/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
 */

@class NSString, NSDictionary, NSObject<OS_dispatch_queue>, MediaControlClient;

@interface FigCPEFPAirPlaySession : NSObject  {
    bool_invalid;
    unsigned int _fairPlayContext;
    NSDictionary *_protectionInfo;
    NSDictionary *_contentInfo;
    MediaControlClient *_mediaControlClient;
    NSString *_mediaControlUUID;
    unsigned int _vodkaVersion;
    struct FPStreamOpaque_ { } *_fairPlaySession;
    NSObject<OS_dispatch_queue> *_serializationQueue;
}


- (void)finalize;
- (void)endSession;
- (void)dealloc;
- (id)mediaControlParamsWithStoreResponse:(id)arg1;
- (id)legacySinfs;
- (id)sicWithPic:(id)arg1;
- (id)createPicRequest;
- (id)initWithFairPlayContext:(unsigned int)arg1 routeInfo:(id)arg2 mediaControlClient:(id)arg3 mediaControlUUID:(id)arg4;
- (void)beginSessionWithCompletionQueue:(id)arg1 completionHandler:(id)arg2;
- (id)initWithFairPlayContext:(unsigned int)arg1 contentInfo:(id)arg2 routeInfo:(id)arg3 mediaControlClient:(id)arg4 mediaControlUUID:(id)arg5;
- (id)initWithFairPlayContext:(unsigned int)arg1 protectionInfo:(id)arg2 routeInfo:(id)arg3 mediaControlClient:(id)arg4 mediaControlUUID:(id)arg5;

@end
