/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
 */

@class NSMutableArray;

@interface FigCaptionLayerPrivate : NSObject  {
    struct OpaqueFigCFCaptionRenderer { } *renderer;
    NSMutableArray *captionElementLayers;
    struct OpaqueFigSimpleMutex { } *renderMutex;
    struct OpaqueFigReentrantMutex { } *layoutSublayersMutex;
}



@end
