/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@class NSArray, TIKeyboardCandidate;

@interface TIAutocorrectionList : NSObject <NSSecureCoding> {
    TIKeyboardCandidate *_autocorrection;
    NSArray *_predictions;
}

@property(readonly) TIKeyboardCandidate * autocorrection;
@property(readonly) NSArray * predictions;
@property(readonly) NSArray * candidates;
@property(readonly) bool shouldAcceptTopCandidate;

+ (id)autocorrectionListWithCandidates:(id)arg1 shouldAcceptTopCandidate:(bool)arg2;
+ (id)listWithAutocorrection:(id)arg1 predictions:(id)arg2;
+ (bool)supportsSecureCoding;

- (id)initWithCandidates:(id)arg1;
- (id)initWithCandidates:(id)arg1 shouldAcceptTopCandidate:(bool)arg2;
- (id)initWithAutocorrection:(id)arg1 predictions:(id)arg2;
- (bool)shouldAcceptTopCandidate;
- (id)predictions;
- (id)autocorrection;
- (id)candidates;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
