/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@class NSString;

@interface TIKeyboardCandidate : NSObject <NSCopying, NSSecureCoding, TIKeyboardCandidateCoding> {
    NSString *_alternativeText;
}

@property(readonly) NSString * candidate;
@property(readonly) NSString * input;
@property(readonly) NSString * label;
@property(copy) NSString * alternativeText;
@property(readonly) unsigned long long wordOriginFeedbackID;
@property(readonly) unsigned long long deleteCount;
@property(readonly) bool isForShortcutConversion;
@property(readonly) bool isAutocorrection;
@property(getter=isExtensionCandidate,readonly) bool extensionCandidate;
@property(getter=isEmojiCandidate,readonly) bool emojiCandidate;
@property(getter=isCompletionCandidate,readonly) bool completionCandidate;
@property(getter=isInlineCompletionCandidate,readonly) bool inlineCompletionCandidate;
@property(getter=isFullwidthCandidate,readonly) bool fullwidthCandidate;
@property(readonly) unsigned int usageTrackingMask;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (bool)supportsSecureCoding;
+ (int)type;

- (bool)isEmojiCandidate;
- (void)encodeWithCandidateResultSetCoder:(id)arg1;
- (id)initWithCandidateResultSetCoder:(id)arg1;
- (bool)isAutocorrection;
- (unsigned long long)wordOriginFeedbackID;
- (unsigned int)usageTrackingMask;
- (bool)isFullwidthCandidate;
- (bool)isInlineCompletionCandidate;
- (bool)isCompletionCandidate;
- (bool)isExtensionCandidate;
- (bool)isForShortcutConversion;
- (id)candidate;
- (void)setAlternativeText:(id)arg1;
- (id)alternativeText;
- (unsigned long long)deleteCount;
- (id)input;
- (id)label;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
