/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@class NSString;

@interface AWDAirPlayScreenSessionStartedOnClient : PBCodable <NSCopying> {
    unsigned long long _timestamp;
    unsigned int _audioCompressionType;
    unsigned int _bonjourMs;
    unsigned int _configMs;
    unsigned int _connectMs;
    unsigned int _prepareMs;
    NSString *_sessionUUID;
    int _status;
    unsigned int _transportType;
    struct { 
        unsigned int timestamp : 1; 
        unsigned int audioCompressionType : 1; 
        unsigned int bonjourMs : 1; 
        unsigned int configMs : 1; 
        unsigned int connectMs : 1; 
        unsigned int prepareMs : 1; 
        unsigned int status : 1; 
        unsigned int transportType : 1; 
    } _has;
}

@property(readonly) bool hasSessionUUID;
@property(retain) NSString * sessionUUID;
@property bool hasTimestamp;
@property unsigned long long timestamp;
@property bool hasStatus;
@property int status;
@property bool hasTransportType;
@property unsigned int transportType;
@property bool hasAudioCompressionType;
@property unsigned int audioCompressionType;
@property bool hasPrepareMs;
@property unsigned int prepareMs;
@property bool hasBonjourMs;
@property unsigned int bonjourMs;
@property bool hasConnectMs;
@property unsigned int connectMs;
@property bool hasConfigMs;
@property unsigned int configMs;


- (unsigned int)configMs;
- (unsigned int)connectMs;
- (unsigned int)bonjourMs;
- (unsigned int)prepareMs;
- (bool)hasConfigMs;
- (void)setHasConfigMs:(bool)arg1;
- (void)setConfigMs:(unsigned int)arg1;
- (bool)hasConnectMs;
- (void)setHasConnectMs:(bool)arg1;
- (void)setConnectMs:(unsigned int)arg1;
- (bool)hasBonjourMs;
- (void)setHasBonjourMs:(bool)arg1;
- (void)setBonjourMs:(unsigned int)arg1;
- (bool)hasPrepareMs;
- (void)setHasPrepareMs:(bool)arg1;
- (void)setPrepareMs:(unsigned int)arg1;
- (unsigned int)audioCompressionType;
- (bool)hasAudioCompressionType;
- (void)setHasAudioCompressionType:(bool)arg1;
- (void)setAudioCompressionType:(unsigned int)arg1;
- (id)sessionUUID;
- (bool)hasSessionUUID;
- (void)setSessionUUID:(id)arg1;
- (unsigned int)transportType;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (void)setHasTransportType:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (bool)hasTransportType;
- (bool)hasTimestamp;
- (bool)hasStatus;
- (void)setHasStatus:(bool)arg1;
- (void)setStatus:(int)arg1;
- (int)status;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;
- (void)setTransportType:(unsigned int)arg1;

@end
