/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@interface AWDIDSWiProxConnectionSuccess : PBCodable <NSCopying> {
    long long _timeToSucceed;
    unsigned long long _timestamp;
    struct { 
        unsigned int timeToSucceed : 1; 
        unsigned int timestamp : 1; 
    } _has;
}

@property bool hasTimestamp;
@property unsigned long long timestamp;
@property bool hasTimeToSucceed;
@property long long timeToSucceed;


- (long long)timeToSucceed;
- (bool)hasTimeToSucceed;
- (void)setHasTimeToSucceed:(bool)arg1;
- (void)setTimeToSucceed:(long long)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (bool)hasTimestamp;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
