/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@class NSString, NSMutableArray;

@interface AWDMMCSError : PBCodable <NSCopying> {
    int _code;
    NSString *_domain;
    NSMutableArray *_underlyingErrors;
    struct { 
        unsigned int code : 1; 
    } _has;
}

@property(readonly) bool hasDomain;
@property(retain) NSString * domain;
@property bool hasCode;
@property int code;
@property(retain) NSMutableArray * underlyingErrors;


- (id)underlyingErrors;
- (id)underlyingErrorsAtIndex:(unsigned long long)arg1;
- (void)clearUnderlyingErrors;
- (unsigned long long)underlyingErrorsCount;
- (void)addUnderlyingErrors:(id)arg1;
- (void)setUnderlyingErrors:(id)arg1;
- (bool)hasDomain;
- (void)setCode:(int)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (void)setDomain:(id)arg1;
- (bool)hasCode;
- (void)setHasCode:(bool)arg1;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (int)code;
- (id)domain;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;

@end
