/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@class NSString;

@interface AWDNFCHardwareExceptionEvent : PBCodable <NSCopying> {
    unsigned long long _timestamp;
    NSString *_exceptionData;
    unsigned int _type;
    struct { 
        unsigned int timestamp : 1; 
        unsigned int type : 1; 
    } _has;
}

@property bool hasTimestamp;
@property unsigned long long timestamp;
@property bool hasType;
@property unsigned int type;
@property(readonly) bool hasExceptionData;
@property(retain) NSString * exceptionData;


- (id)exceptionData;
- (bool)hasExceptionData;
- (void)setExceptionData:(id)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)hasType;
- (void)setHasType:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (bool)hasTimestamp;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)type;
- (void)setTimestamp:(unsigned long long)arg1;
- (void)setType:(unsigned int)arg1;
- (unsigned long long)timestamp;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;

@end
