/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@interface AWDSiriServerConnectionOpen : PBCodable <NSCopying> {
    unsigned long long _duration;
    unsigned long long _timestamp;
    int _connectionType;
    struct { 
        unsigned int duration : 1; 
        unsigned int timestamp : 1; 
        unsigned int connectionType : 1; 
    } _has;
}

@property bool hasTimestamp;
@property unsigned long long timestamp;
@property bool hasDuration;
@property unsigned long long duration;
@property bool hasConnectionType;
@property int connectionType;


- (bool)hasConnectionType;
- (void)setHasConnectionType:(bool)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)hasDuration;
- (void)setHasDuration:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setConnectionType:(int)arg1;
- (int)connectionType;
- (bool)hasTimestamp;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (void)setDuration:(unsigned long long)arg1;
- (unsigned long long)duration;
- (unsigned long long)timestamp;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
