/* Generated by RuntimeBrowser.
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@class NSString;

@interface AWDSiriServerConnectionFailed : PBCodable <NSCopying> {
    long long _errorCode;
    unsigned long long _timestamp;
    int _connectionType;
    NSString *_errorDomain;
    struct { 
        unsigned int errorCode : 1; 
        unsigned int timestamp : 1; 
        unsigned int connectionType : 1; 
    } _has;
}

@property bool hasTimestamp;
@property unsigned long long timestamp;
@property(readonly) bool hasErrorDomain;
@property(retain) NSString * errorDomain;
@property bool hasErrorCode;
@property long long errorCode;
@property bool hasConnectionType;
@property int connectionType;


- (bool)hasConnectionType;
- (void)setHasConnectionType:(bool)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)hasErrorCode;
- (void)setHasErrorCode:(bool)arg1;
- (void)setErrorCode:(long long)arg1;
- (bool)hasErrorDomain;
- (void)setErrorDomain:(id)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setConnectionType:(int)arg1;
- (int)connectionType;
- (long long)errorCode;
- (bool)hasTimestamp;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)errorDomain;

@end
