/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@class NSString;

@interface CTCall : NSObject  {
    NSString *_callState;
    NSString *_callID;
}

@property(copy) NSString * callState;
@property(copy) NSString * callID;

+ (id)callForCTCallRef:(struct __CTCall { }*)arg1;

- (void)setCallID:(id)arg1;
- (id)callID;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;
- (void)setCallState:(id)arg1;
- (id)callState;

@end
