/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@class NSString;

@interface CTPhoneNumber : NSObject <NSCopying, CTMessageAddress> {
    NSString *_digits;
    NSString *_countryCode;
    bool_isShortCode;
}

@property(readonly) NSString * digits;
@property(readonly) NSString * countryCode;
@property bool isShortCode;

+ (bool)isValidPhoneNumberChar:(unsigned short)arg1;
+ (bool)isValidPhoneNumber:(id)arg1;
+ (id)phoneNumberWithDigits:(id)arg1 countryCode:(id)arg2;

- (id)countryCode;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)digits;
- (void)setIsShortCode:(bool)arg1;
- (long long)numberOfDigitsForShortCodeNumber;
- (id)formatForCallingCountry:(id)arg1;
- (id)canonicalFormat;
- (bool)isShortCode;
- (id)encodedString;
- (id)initWithDigits:(id)arg1 countryCode:(id)arg2;

@end
