/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
 */

@class NSString;

@interface PCDistributedLock : NSObject <NSLocking> {
    NSString *_path;
    int _fd;
}


- (bool)_lockBlocking:(bool)arg1;
- (id)initWithName:(id)arg1;
- (id)initWithPath:(id)arg1;
- (void)unlock;
- (void)lock;
- (void)dealloc;
- (bool)tryLock;

@end
