/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
 */

@class NSString, CUTWeakReference, NSObject<OS_dispatch_queue>, PCInterfaceUsabilityMonitor, <PCInterfaceUsabilityMonitorDelegate>;

@interface PCWWANUsabilityMonitor : NSObject <PCInterfaceUsabilityMonitorProtocol, PCInterfaceUsabilityMonitorDelegate> {
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSObject<OS_dispatch_queue> *_ivarQueue;
    NSObject<OS_dispatch_queue> *_monitorDelegateQueue;
    CUTWeakReference *_delegateReference;
    bool_isInCall;
    bool_isInHighPowerState;
    bool_trackUsability;
    unsigned long long _thresholdOffTransitionCount;
    double _trackedTimeInterval;
    NSString *_interfaceName;
    PCInterfaceUsabilityMonitor *_interfaceMonitor;
    struct __CFString { } *_currentRAT;
    int _powerlogCDRXToken;
    struct __CTServerConnection { } *_telephonyServer;
    int _wwanContextID;
    NSObject<OS_dispatch_queue> *_ctServerQueue;
}

@property(readonly) struct __CFString { }* currentRAT;
@property(readonly) bool isLTEWithCDRX;
@property(readonly) struct __CFString { }* wwanInterfaceName;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) long long interfaceIdentifier;
@property(readonly) int linkQuality;
@property(readonly) bool isInterfaceUsable;
@property(readonly) bool isInterfaceHistoricallyUsable;
@property(readonly) bool isInternetReachable;
@property(retain,readonly) NSString * linkQualityString;
@property(readonly) bool isPoorLinkQuality;
@property(readonly) bool isBadLinkQuality;
@property(readonly) bool isRadioHot;
@property <PCInterfaceUsabilityMonitorDelegate> * delegate;


- (long long)interfaceIdentifier;
- (int)linkQuality;
- (void)_adjustInterfaceNameForWWANContextID:(int)arg1;
- (void)_setupWWANMonitor;
- (id)initWithDelegateQueue:(id)arg1;
- (void)_forwardConfigurationOnIvarQueue;
- (bool)isLTEWithCDRX;
- (struct __CFString { }*)currentRAT;
- (bool)isRadioHot;
- (void)setTrackUsability:(bool)arg1;
- (void)setThresholdOffTransitionCount:(unsigned long long)arg1;
- (void)setTrackedTimeInterval:(double)arg1;
- (void)_callDelegateOnIvarQueueWithBlock:(id)arg1;
- (bool)isBadLinkQuality;
- (void)interfaceReachabilityChanged:(id)arg1;
- (void)interfaceLinkQualityChanged:(id)arg1 previousLinkQuality:(int)arg2;
- (bool)isInterfaceHistoricallyUsable;
- (id)linkQualityString;
- (struct __CFString { }*)wwanInterfaceName;
- (void)_handleTelephonyNotificationWithName:(struct __CFString { }*)arg1 userInfo:(struct __CFDictionary { }*)arg2;
- (bool)isPoorLinkQuality;
- (bool)isInterfaceUsable;
- (bool)isInternetReachable;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end
