/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSArray, NSMutableDictionary, NSString, SSDialogButton, NSDictionary;

@interface SSDialog : NSObject  {
    NSArray *_buttons;
    NSMutableDictionary *_dialogDictionary;
}

@property(copy) NSString * message;
@property(copy) NSString * title;
@property(copy) NSArray * buttons;
@property(retain) SSDialogButton * defaultButton;
@property(readonly) NSDictionary * dialogDictionary;
@property(readonly) NSString * dialogKind;


- (id)dialogDictionary;
- (void)setButtons:(id)arg1;
- (id)dialogKind;
- (id)initWithDialogDictionary:(id)arg1;
- (id)buttons;
- (id)valueForProperty:(id)arg1;
- (void)_setValue:(id)arg1 forProperty:(id)arg2;
- (void)setMessage:(id)arg1;
- (void)setDefaultButton:(id)arg1;
- (id)defaultButton;
- (id)message;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)init;
- (void)dealloc;

@end
