/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSURLRequest, NSString, <SSDownloadManifestRequestDelegate>;

@interface SSDownloadManifestRequest : SSRequest <SSXPCCoding> {
    long long _manifestFormat;
    bool_shouldHideUserPrompts;
    NSURLRequest *_urlRequest;
}

@property(readonly) NSURLRequest * URLRequest;
@property bool shouldHideUserPrompts;
@property <SSDownloadManifestRequestDelegate> * delegate;
@property long long manifestFormat;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (long long)manifestFormat;
- (bool)shouldHideUserPrompts;
- (void)setShouldHideUserPrompts:(bool)arg1;
- (void)startWithManifestResponseBlock:(id)arg1;
- (void)setManifestFormat:(long long)arg1;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (bool)start;
- (id)init;
- (void)dealloc;
- (id)initWithURLRequest:(id)arg1;
- (id)URLRequest;
- (void)startWithCompletionBlock:(id)arg1;

@end
