/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSString, NSNumber;

@interface SSFamilyMember : NSObject <SSXPCCoding> {
    NSString *_firstName;
    NSString *_iCloudAccountName;
    NSNumber *_iCloudIdentifier;
    NSNumber *_iTunesIdentifier;
    NSString *_lastName;
    bool_me;
    bool_sharingPurchases;
}

@property(retain) NSString * iCloudAccountName;
@property(retain) NSNumber * iCloudIdentifier;
@property(retain) NSNumber * iTunesIdentifier;
@property(retain) NSString * firstName;
@property(retain) NSString * lastName;
@property(getter=isMe) bool me;
@property(getter=isSharingPurchases) bool sharingPurchases;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)setSharingPurchases:(bool)arg1;
- (bool)isSharingPurchases;
- (void)setMe:(bool)arg1;
- (void)setITunesIdentifier:(id)arg1;
- (void)setICloudIdentifier:(id)arg1;
- (void)setICloudAccountName:(id)arg1;
- (id)iTunesIdentifier;
- (id)iCloudAccountName;
- (id)iCloudIdentifier;
- (void)setLastName:(id)arg1;
- (void)setFirstName:(id)arg1;
- (id)lastName;
- (id)firstName;
- (bool)isMe;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (id)description;

@end
