/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSDate, NSString, NSArray, SSURLConnectionRequest, SSItemOffer, NSURL, NSDictionary, NSMutableArray, SSItemImageCollection, NSNumber;

@interface SSItem : NSObject <SSURLConnectionRequestDelegate> {
    NSDate *_expirationDate;
    NSArray *_offers;
    NSDictionary *_properties;
    NSString *_tellAFriendBody;
    NSString *_tellAFriendBodyMIMEType;
    NSMutableArray *_tellAFriendHandlers;
    SSURLConnectionRequest *_tellAFriendRequest;
    NSString *_tellAFriendSubject;
}

@property(readonly) NSNumber * ITunesStoreIdentifier;
@property(readonly) NSArray * allItemOffers;
@property(readonly) SSItemOffer * defaultItemOffer;
@property(readonly) NSString * artistName;
@property(readonly) NSDate * expirationDate;
@property(readonly) NSString * itemTitle;
@property(readonly) NSString * itemKind;
@property(getter=isRestricted,readonly) bool restricted;
@property(getter=isHighDefinition,readonly) bool highDefinition;
@property(getter=isGameCenterEnabled,readonly) bool gameCenterEnabled;
@property(readonly) NSURL * viewItemURL;
@property(readonly) float averageUserRating;
@property(readonly) long long numberOfUserRatings;
@property(readonly) SSItemImageCollection * imageCollection;
@property(readonly) NSArray * thumbnailImages;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)genreName;
- (bool)isGameCenterEnabled;
- (id)tweetURL;
- (id)tweetInitialText;
- (id)tellAFriendSubject;
- (id)tellAFriendBodyURL;
- (id)tellAFriendBodyMIMEType;
- (id)tellAFriendBody;
- (id)relatedItemsForRelationType:(id)arg1;
- (id)playableMedia;
- (id)initWithItemDictionary:(id)arg1;
- (id)priceDisplay;
- (id)softwareType;
- (float)averageUserRating;
- (id)viewReviewsURL;
- (id)sendGiftURL;
- (id)viewItemURL;
- (id)thumbnailImages;
- (long long)numberOfPrintedPages;
- (void)loadTellAFriendMessageWithCompletionHandler:(id)arg1;
- (id)allItemOffers;
- (void)_finishTellAFriendLoadWithError:(id)arg1;
- (id)_tellAFriendDictionary;
- (id)_offers;
- (void)urlConnectionRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (id)itemOfferForIdentifier:(id)arg1;
- (id)rawItemDictionary;
- (id)imageCollection;
- (id)videoDetails;
- (id)seriesName;
- (id)podcastEpisodeGUID;
- (id)numberOfItemsInCollection;
- (id)numberOfCollectionsInCollectionGroup;
- (id)genreIdentifier;
- (id)episodeSortIdentifier;
- (id)episodeIdentifier;
- (id)composerName;
- (id)collectionIndexInCollectionGroup;
- (id)collectionArtistName;
- (id)artistIdentifier;
- (id)preOrderIdentifier;
- (id)defaultItemOffer;
- (id)podcastFeedURL;
- (id)indexInCollection;
- (bool)isHighDefinition;
- (bool)isRestricted;
- (id)releaseDateString;
- (long long)numberOfUserRatings;
- (id)itemKind;
- (id)expirationDate;
- (id)collectionIdentifier;
- (id)collectionName;
- (id)longDescription;
- (id)ITunesStoreIdentifier;
- (id)artistName;
- (id)contentRating;
- (id)networkName;
- (id)seasonNumber;
- (id)bundleVersion;
- (void)_setExpirationDate:(id)arg1;
- (id)valueForProperty:(id)arg1;
- (id)shortDescription;
- (id)itemTitle;
- (id)bundleIdentifier;
- (id)description;
- (void)dealloc;
- (void)requestDidFinish:(id)arg1;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (id)releaseDate;
- (bool)isCompilation;
- (id)buyParameters;
- (id)mediaKind;

@end
