/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSMutableDictionary, NSString, CLLocation, NSNumber;

@interface SSLookupProperties : NSObject <NSCopying, SSXPCCoding> {
    CLLocation *_location;
    long long _localizationStyle;
    NSMutableDictionary *_requestParameters;
    NSNumber *_timeoutInterval;
}

@property(copy) NSString * keyProfile;
@property long long localizationStyle;
@property(copy) CLLocation * location;
@property(copy) NSNumber * timeoutInterval;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (long long)localizationStyle;
- (id)valueForRequestParameter:(id)arg1;
- (id)copyRequestParameters;
- (id)keyProfile;
- (void)setLocation:(id)arg1;
- (id)timeoutInterval;
- (void)setTimeoutInterval:(id)arg1;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (id)location;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)setValue:(id)arg1 forRequestParameter:(id)arg2;
- (void)setLocalizationStyle:(long long)arg1;
- (void)setKeyProfile:(id)arg1;

@end
