/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSString;

@interface SSMetricsSearchEvent : SSMetricsBaseEvent  {
}

@property(retain) NSString * searchTerm;
@property(retain) NSString * actionType;
@property(retain) id actionDetails;
@property(retain) NSString * targetIdentifier;
@property(retain) NSString * targetType;
@property(retain) NSString * targetURL;


- (id)targetURL;
- (id)actionDetails;
- (id)targetIdentifier;
- (id)targetType;
- (void)setLocationWithEventLocations:(id)arg1;
- (void)setActionDetails:(id)arg1;
- (void)setTargetType:(id)arg1;
- (void)setTargetIdentifier:(id)arg1;
- (void)setTargetURL:(id)arg1;
- (id)actionType;
- (void)setActionType:(id)arg1;
- (id)init;
- (void)setSearchTerm:(id)arg1;
- (id)searchTerm;

@end
