/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSMetricsEventTableEntity : SSSQLiteEntity  {
}

+ (id)databaseTable;

- (id)reportingJSON;
- (id)reportingDictionary;

@end
