/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSString, <SSPurchaseManagerDelegate>, NSObject<OS_dispatch_queue>, SSXPCConnection;

@interface SSPurchaseManager : NSObject  {
    NSObject<OS_dispatch_queue> *_completionBlockQueue;
    <SSPurchaseManagerDelegate> *_delegate;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSString *_managerIdentifier;
    SSXPCConnection *_requestConnection;
    SSXPCConnection *_responseConnection;
}

@property(readonly) NSString * managerIdentifier;
@property <SSPurchaseManagerDelegate> * delegate;


- (void)_reconnectForDaemonLaunch;
- (id)managerIdentifier;
- (void)insertPurchases:(id)arg1 afterPurchase:(id)arg2 withCompletionBlock:(id)arg3;
- (id)_newEncodedArrayWithPurchases:(id)arg1;
- (void)_sendCompletionBlock:(id)arg1 forStandardReply:(id)arg2;
- (id)_newEncodedArrayWithPurchaseIdentifiers:(id)arg1;
- (bool)_resultForReply:(id)arg1 error:(id*)arg2;
- (void)_handleMessage:(id)arg1 fromConnection:(id)arg2;
- (void)_sendCompletionBlock:(id)arg1 forGetPurchasesReply:(id)arg2;
- (void)_sendMessage:(long long)arg1 withPurchaseIdentifiers:(id)arg2 afterPurchase:(id)arg3 completionBlock:(id)arg4;
- (void)_sendMessage:(long long)arg1 withPurchases:(id)arg2 afterPurchase:(id)arg3 completionBlock:(id)arg4;
- (void)_connectToDaemon;
- (id)_responseConnection;
- (id)_requestConnection;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void)movePurchases:(id)arg1 afterPurchase:(id)arg2 withCompletionBlock:(id)arg3;
- (void)cancelPurchases:(id)arg1 withCompletionBlock:(id)arg2;
- (void)addPurchases:(id)arg1 withCompletionBlock:(id)arg2;
- (void)getPurchasesUsingBlock:(id)arg1;
- (id)initWithManagerIdentifier:(id)arg1;

@end
