/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSObject<OS_dispatch_queue>, SSXPCConnection, SSUpdatesDatabase;

@interface SSSoftwareUpdatesStore : NSObject  {
    NSObject<OS_dispatch_queue> *_calloutQueue;
    SSXPCConnection *_connection;
    SSUpdatesDatabase *_database;
    bool_didMigration;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    void *_mobileCoreServices;
    bool_useLocalRead;
    bool_useLocalWrite;
}

+ (id)databasePath;

- (id)updateWithItemIdentifier:(long long)arg1;
- (void)showApplicationBadgeForPendingUpdates;
- (void)removeUpdateBulletins;
- (void)hideApplicationBadgeForPendingUpdates;
- (void)clearExpiredUpdateHistoryWithCompletionBlock:(id)arg1;
- (bool)_migrateReadOnlyDatabase;
- (void)_readUsingSessionBlock:(id)arg1;
- (id)_copyUpdatesWithSession:(id)arg1 predicate:(id)arg2;
- (id)_copyUpdates;
- (void)reloadFromServerWithCompletionBlock:(id)arg1;
- (void)getUpdatesWithCompletionBlock:(id)arg1;
- (id)init;
- (void)dealloc;

@end
