/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSData, NSString, NSURL, NSArray, NSDictionary, NSInputStream, NSObject<OS_dispatch_queue>;

@interface SSURLRequestProperties : NSObject <SSXPCCoding, NSCoding, NSCopying, NSMutableCopying> {
    long long _allowedRetryCount;
    bool_allowsBootstrapCellularData;
    unsigned long long _cachePolicy;
    NSString *_clientAuditBundleIdentifier;
    NSData *_clientAuditTokenData;
    NSString *_clientIdentifier;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    long long _expectedContentLength;
    NSData *_httpBody;
    NSInputStream *_httpBodyStream;
    NSDictionary *_httpHeaders;
    NSString *_httpMethod;
    bool_isITunesStoreRequest;
    long long _kbsyncType;
    bool_largeDownload;
    unsigned long long _networkServiceType;
    NSDictionary *_requestParameters;
    BOOL _requiresExtendedValidationCertificates;
    bool_requiresHTTPS;
    bool_shouldDecodeResponse;
    bool_shouldDisableCellular;
    bool_shouldDisableCellularFallback;
    bool_shouldProcessProtocol;
    bool_shouldSendSecureToken;
    bool_shouldSetCookies;
    double _timeoutInterval;
    NSString *_urlBagKey;
    long long _urlBagType;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _urlBagURLBlock;

    NSArray *_urls;
    NSArray *_userAgentComponents;
}

@property(readonly) long long allowedRetryCount;
@property(copy,readonly) NSString * clientIdentifier;
@property(readonly) unsigned long long cachePolicy;
@property(readonly) long long expectedContentLength;
@property(copy,readonly) NSData * HTTPBody;
@property(copy,readonly) NSDictionary * HTTPHeaders;
@property(copy,readonly) NSString * HTTPMethod;
@property(getter=isITunesStoreRequest,readonly) bool ITunesStoreRequest;
@property(readonly) unsigned long long networkServiceType;
@property(copy,readonly) NSDictionary * requestParameters;
@property(readonly) double timeoutInterval;
@property(copy,readonly) NSString * URLBagKey;
@property(retain,readonly) NSURL * URL;
@property(copy,readonly) NSArray * userAgentComponents;
@property(readonly) bool allowsBootstrapCellularData;
@property(readonly) bool canBeResolved;
@property(copy,readonly) NSString * clientAuditBundleIdentifier;
@property(copy,readonly) NSData * clientAuditTokenData;
@property(retain,readonly) NSInputStream * HTTPBodyStream;
@property(readonly) long long KBSyncType;
@property(getter=isLargeDownload,readonly) bool largeDownload;
@property(readonly) bool requiresExtendedValidationCertificates;
@property(readonly) bool requiresHTTPS;
@property(readonly) bool shouldAddKBSyncData;
@property(readonly) bool shouldDecodeResponse;
@property(readonly) bool shouldDisableCellularFallback;
@property(readonly) bool shouldDisableCellular;
@property(readonly) bool shouldProcessProtocol;
@property(readonly) bool shouldSendSecureToken;
@property(readonly) bool shouldSetCookies;
@property(readonly) long long URLBagType;
@property(copy,readonly) id URLBagURLBlock;
@property(copy,readonly) NSArray * URLs;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)_initCommon;
- (id)HTTPHeaders;
- (id)URLBagURLBlock;
- (id)copyURLRequest;
- (id)requestParameters;
- (bool)canBeResolved;
- (long long)expectedContentLength;
- (bool)shouldDisableCellularFallback;
- (bool)shouldDisableCellular;
- (bool)shouldAddKBSyncData;
- (bool)requiresHTTPS;
- (bool)requiresExtendedValidationCertificates;
- (long long)KBSyncType;
- (bool)isLargeDownload;
- (id)clientAuditTokenData;
- (id)clientAuditBundleIdentifier;
- (bool)shouldSetCookies;
- (bool)shouldSendSecureToken;
- (bool)shouldProcessProtocol;
- (long long)allowedRetryCount;
- (id)userAgentComponents;
- (bool)allowsBootstrapCellularData;
- (bool)shouldDecodeResponse;
- (bool)isITunesStoreRequest;
- (id)URLBagKey;
- (long long)URLBagType;
- (id)HTTPMethod;
- (unsigned long long)cachePolicy;
- (double)timeoutInterval;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (id)URLs;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)URL;
- (id)initWithURL:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (bool)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithURLRequest:(id)arg1;
- (id)clientIdentifier;
- (unsigned long long)networkServiceType;
- (id)HTTPBody;
- (id)HTTPBodyStream;

@end
