/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSString, NSNumber, NSURL;

@interface SSVContentLink : NSObject  {
    NSString *_categoryName;
    long long _contentKind;
    NSNumber *_itemIdentifier;
    NSString *_itemTitle;
    NSString *_providerName;
    NSString *_searchTerm;
    long long _targetApplication;
}

@property long long contentKind;
@property long long targetApplication;
@property(readonly) NSURL * URL;
@property(copy) NSString * categoryName;
@property(copy) NSNumber * itemIdentifier;
@property(copy) NSString * itemTitle;
@property(copy) NSString * providerName;
@property(copy) NSString * searchTerm;


- (void)setTargetApplication:(long long)arg1;
- (void)setProviderName:(id)arg1;
- (void)setItemTitle:(id)arg1;
- (void)setContentKind:(long long)arg1;
- (id)_stringForContentKind:(long long)arg1;
- (id)_URLSchemeWithApplication:(long long)arg1;
- (long long)_targetApplicationWithContentKind:(long long)arg1;
- (long long)contentKind;
- (long long)targetApplication;
- (void)setCategoryName:(id)arg1;
- (id)categoryName;
- (void)setItemIdentifier:(id)arg1;
- (id)itemIdentifier;
- (id)providerName;
- (void).cxx_destruct;
- (id)itemTitle;
- (id)URL;
- (void)setSearchTerm:(id)arg1;
- (id)searchTerm;

@end
