/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSArray, NSString;

@interface SSVDialogResponse : NSObject <NSCopying, SSXPCCoding> {
    long long _selectedButtonIndex;
    NSArray *_textFieldValues;
}

@property long long selectedButtonIndex;
@property(copy) NSArray * textFieldValues;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)textFieldValues;
- (void)setTextFieldValues:(id)arg1;
- (void)setSelectedButtonIndex:(long long)arg1;
- (long long)selectedButtonIndex;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
