/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSDictionary, NSMutableDictionary;

@interface SSVRedeemCodeItem : NSObject  {
    NSMutableDictionary *_dictionary;
}

@property(readonly) NSDictionary * redeemCodeDictionary;
@property(readonly) long long itemIdentifier;


- (id)redeemCodeDictionary;
- (id)initWithRedeemCodeDictionary:(id)arg1;
- (id)initWithLookupItem:(id)arg1;
- (long long)itemIdentifier;
- (void).cxx_destruct;

@end
