/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@class NSObject<OS_dispatch_queue>, NSMutableDictionary, NSString;

@interface BSFileLogManager : NSObject <BSFileLoggerDelegate> {
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_loggersByName;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)sharedInstance;

- (void)reloadFromDefaults;
- (id)loggerForName:(id)arg1;
- (void)loggerEnabledStateChanged:(id)arg1;
- (void)_queue_addLogger:(id)arg1;
- (bool)_queue_isClass:(Class)arg1 aKindOfClass:(Class)arg2;
- (void)_queue_enableOrDisableLoggerIfNecessary:(id)arg1;
- (void)_queue_loadFileLoggers;
- (void)flush;
- (id)init;
- (void)dealloc;

@end
