/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@class NSObject<OS_xpc_object>;

@interface BSXPCReply : NSObject  {
    NSObject<OS_xpc_object> *_message;
}

+ (id)messageWithReply:(id)arg1;

- (void)sendReply:(id)arg1;
- (long long)messageKind;
- (id)initWithReply:(id)arg1;
- (id)message;
- (void)dealloc;

@end
