/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
 */

@class NSData, NSString;

@interface CBUUID : NSObject <NSCopying> {
    unsigned char _bytes[16];
    BOOL _type;
}

@property(readonly) NSData * data;
@property(readonly) NSString * UUIDString;

+ (id)UUIDWithString:(id)arg1;
+ (id)UUIDWithNSUUID:(id)arg1;
+ (id)UUIDWithCFUUID:(struct __CFUUID { }*)arg1;
+ (id)UUIDWithData:(id)arg1;

- (id)initWithString:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)data;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)UUIDString;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)initWithNSUUID:(id)arg1;
- (id)initWithCFUUID:(struct __CFUUID { }*)arg1;

@end
