/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@class CPLRUDictionaryNode;

@interface CPLRUDictionary : NSObject  {
    struct __CFDictionary { } *_dictionary;
    unsigned long long _maxCount;
    CPLRUDictionaryNode *_head;
    CPLRUDictionaryNode *_tail;
}

+ (id)dictionaryWithMaximumCapacity:(unsigned long long)arg1;

- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)initWithMaximumCapacity:(unsigned long long)arg1;
- (void)removeObjectForKey:(id)arg1;
- (id)description;
- (void)removeAllObjects;
- (unsigned long long)count;
- (void)dealloc;
- (id)allKeys;
- (void)_moveNodeToFront:(id)arg1;
- (void)_removeNode:(id)arg1;
- (void)_addNodeToFront:(id)arg1;
- (void)_removeNodeFromLinkedList:(id)arg1;
- (id)objectForKeyWithoutAffectingLRU:(id)arg1;
- (id)allValuesInLRUOrder;
- (id)allKeysInLRUOrder;
- (unsigned long long)linkedListCount;

@end
