/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FaceCore.framework/FaceCore
 */

@interface FCRImage : NSObject  {
    unsigned long long width;
    unsigned long long height;
    unsigned long long bytesPerRow;
    char *rawDataBuffer;
    char *alignedDataBuffer;
    boolfreeBufferWhenDone;
}

@property unsigned long long width;
@property unsigned long long height;
@property unsigned long long bytesPerRow;


- (char *)getAlignedImageData;
- (id)initWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 bytesPerRow:(unsigned long long)arg3 buffer:(char *)arg4 freeBufferWhenDone:(bool)arg5;
- (void)setHeight:(unsigned long long)arg1;
- (void)setWidth:(unsigned long long)arg1;
- (unsigned long long)height;
- (unsigned long long)width;
- (void)dealloc;
- (unsigned long long)bytesPerRow;
- (void)setBytesPerRow:(unsigned long long)arg1;

@end
