/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMDocument;

@interface DOMAbstractView : DOMObject  {
}

@property(readonly) DOMDocument * document;


- (id)document;
- (void)dealloc;
- (void)_disconnectFrame;

@end
