/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString, DOMCSSStyleSheet, DOMCSSRule;

@interface DOMCSSRule : DOMObject  {
}

@property(readonly) unsigned short type;
@property(copy) NSString * cssText;
@property(readonly) DOMCSSStyleSheet * parentStyleSheet;
@property(readonly) DOMCSSRule * parentRule;


- (id)parentRule;
- (id)parentStyleSheet;
- (id)cssText;
- (void)finalize;
- (void)setCssText:(id)arg1;
- (unsigned short)type;
- (void)dealloc;

@end
