/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMHTMLOListElement : DOMHTMLElement  {
}

@property bool compact;
@property int start;
@property(copy) NSString * type;


- (void)setReversed:(bool)arg1;
- (bool)reversed;
- (void)setCompact:(bool)arg1;
- (bool)compact;
- (void)setStart:(int)arg1;
- (int)start;
- (id)type;
- (void)setType:(id)arg1;

@end
