/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMNodeList;

@interface DOMHTMLProgressElement : DOMHTMLElement  {
}

@property double value;
@property double max;
@property(readonly) double position;
@property(readonly) DOMNodeList * labels;


- (void)setMax:(double)arg1;
- (double)max;
- (id)labels;
- (double)position;
- (double)value;
- (void)setValue:(double)arg1;

@end
