/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMHTMLScriptElement : DOMHTMLElement  {
}

@property(copy) NSString * text;
@property(copy) NSString * htmlFor;
@property(copy) NSString * event;
@property(copy) NSString * charset;
@property bool defer;
@property(copy) NSString * src;
@property(copy) NSString * type;


- (void)setDefer:(bool)arg1;
- (bool)defer;
- (void)setAsync:(bool)arg1;
- (bool)async;
- (void)setHtmlFor:(id)arg1;
- (id)htmlFor;
- (void)setCrossOrigin:(id)arg1;
- (id)crossOrigin;
- (void)setSrc:(id)arg1;
- (id)src;
- (void)setCharset:(id)arg1;
- (id)charset;
- (id)event;
- (void)setEvent:(id)arg1;
- (void)setText:(id)arg1;
- (id)text;
- (id)type;
- (void)setType:(id)arg1;

@end
