/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLinearAlgebra.dylib
 */

@interface OS_la_object : OS_object <OS_la_object> {
}


- (id)debugDescription;
- (id)description;
- (id)init;
- (void)_dispose;

@end
