/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@class NSString, NSDictionary, NSData, UIImage;

@interface SBSCardItem : NSObject <NSCopying, NSSecureCoding> {
    bool_requiresPasscode;
    NSString *_identifier;
    NSData *_iconData;
    NSString *_title;
    NSString *_body;
    NSString *_bundleName;
    NSData *_attachmentData;
    NSDictionary *_userInfo;
    UIImage *_thumbnail;
}

@property(copy) NSString * identifier;
@property(copy) NSData * iconData;
@property(copy) NSString * title;
@property(copy) NSString * body;
@property bool requiresPasscode;
@property(copy) NSString * bundleName;
@property(copy) NSData * attachmentData;
@property(copy) NSDictionary * userInfo;
@property(copy) UIImage * thumbnail;

+ (bool)supportsSecureCoding;

- (void)setIconData:(id)arg1;
- (id)bundleName;
- (id)initWithIdentifier:(id)arg1 iconData:(id)arg2 title:(id)arg3 body:(id)arg4 classification:(long long)arg5 bundleName:(id)arg6 userInfo:(id)arg7;
- (void)setAttachmentData:(id)arg1;
- (id)attachmentData;
- (bool)requiresPasscode;
- (id)initWithIdentifier:(id)arg1 iconData:(id)arg2 title:(id)arg3 body:(id)arg4 requiresPasscode:(bool)arg5 bundleName:(id)arg6 userInfo:(id)arg7;
- (id)initWithIdentifier:(id)arg1 iconData:(id)arg2 title:(id)arg3 body:(id)arg4 requiresPasscode:(bool)arg5 bundleName:(id)arg6 attachmentData:(id)arg7 userInfo:(id)arg8;
- (void)setRequiresPasscode:(bool)arg1;
- (void)setBundleName:(id)arg1;
- (id)iconData;
- (void)setBody:(id)arg1;
- (void)setThumbnail:(id)arg1;
- (id)thumbnail;
- (void)setIdentifier:(id)arg1;
- (id)body;
- (id)sortDate;
- (id)userInfo;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setUserInfo:(id)arg1;
- (id)title;
- (id)identifier;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
