/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/UserFS.framework/UserFS
 */

@class NSString, NSObject<OS_xpc_object>;

@interface UserFSVolume : NSObject  {
    bool_isLocked;
    NSString *_deviceName;
    NSObject<OS_xpc_object> *_connection;
}

@property(copy,readonly) NSString * deviceName;
@property(readonly) bool isLocked;
@property(retain) NSObject<OS_xpc_object> * connection;

+ (bool)prepareToAccessDeviceName:(id)arg1 error:(id*)arg2;
+ (id)volumeWithDeviceName:(id)arg1 error:(id*)arg2;

- (bool)deleteFiles:(id)arg1 error:(id*)arg2;
- (bool)flushAndReturnError:(id*)arg1;
- (id)rootDirectoryAndReturnError:(id*)arg1;
- (id)deviceName;
- (void)setConnection:(id)arg1;
- (id)connection;
- (void).cxx_destruct;
- (bool)isLocked;
- (void)dealloc;
- (bool)closeAndReturnError:(id*)arg1;
- (id)initWithDeviceName:(id)arg1 error:(id*)arg2;
- (id)itemAtPath:(id)arg1 error:(id*)arg2;

@end
