/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataMigration.framework/DataMigration
 */

@class NSString;

@interface DMConnection : DMXPCConnection <DMMigratorServiceProtocol> {
    NSString *_lastPlugin;
}

@property(readonly) NSString * lastPlugin;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)testMigrationUIWithProgress:(bool)arg1 forceInvert:(bool)arg2 completion:(id)arg3;
- (id)lastPlugin;
- (void)migrateWithCompletion:(id)arg1;
- (void)orderedPluginIdentifiersWithCompletion:(id)arg1;
- (void).cxx_destruct;
- (void)handleMessage:(id)arg1;

@end
