/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class NSString, <MTLDevice>, _MTLCommandBuffer<MTLCommandBuffer>;

@interface _MTLCommandEncoder : NSObject  {
    <MTLDevice> *_device;
    NSString *_label;
    _MTLCommandBuffer<MTLCommandBuffer> *_commandBuffer;
}

@property(readonly) <MTLDevice> * device;
@property(copy) NSString * label;


- (id)device;
- (void)setLabel:(id)arg1;
- (id)label;
- (id)description;
- (void)dealloc;
- (id)initWithCommandBuffer:(id)arg1;
- (id)commandBuffer;
- (void)popDebugGroup;
- (void)pushDebugGroup:(id)arg1;
- (void)insertDebugSignpost:(id)arg1;
- (void)endEncoding;

@end
