/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class MTLRenderPassDescriptor, <MTLCommandQueue>, <MTLDevice>, NSString, _MTLCommandBuffer<MTLCommandBuffer>;

@interface _MTLParallelRenderCommandEncoder : NSObject <MTLParallelRenderCommandEncoder> {
    <MTLDevice> *_device;
    <MTLCommandQueue> *_queue;
    NSString *_label;
    _MTLCommandBuffer<MTLCommandBuffer> *_commandBuffer;
    MTLRenderPassDescriptor *_renderPassDescriptor;
    struct _opaque_pthread_mutex_t { 
        long long __sig; 
        BOOL __opaque[56]; 
    } _lock;
    unsigned long long _commandBuffersSize;
    unsigned long long _commandBuffersCount;
    id *_commandBuffers;
    bool_retainedReferences;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) <MTLDevice> * device;
@property(copy) NSString * label;


- (id)device;
- (void)setLabel:(id)arg1;
- (id)label;
- (id)description;
- (void)dealloc;
- (id)sampledRenderCommandEncoderWithProgramInfoBuffer:(struct { unsigned int x1 : 8; unsigned int x2 : 24; unsigned int x3; unsigned long long x4; unsigned long long x5; }*)arg1 capacity:(unsigned long long)arg2;
- (id)initWithCommandBuffer:(id)arg1 renderPassDescriptor:(id)arg2;
- (id)renderCommandEncoder;
- (id)_renderCommandEncoderCommon;
- (id)commandBuffer;
- (void)popDebugGroup;
- (void)pushDebugGroup:(id)arg1;
- (void)insertDebugSignpost:(id)arg1;
- (void)endEncoding;

@end
