/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class MTLCompileOptions;

@interface MTLDebugLibrary : MTLToolsLibrary  {
    unsigned long long _type;
    id _code;
    MTLCompileOptions *_compileOptions;
}

@property unsigned long long type;
@property(copy) id code;
@property(copy) MTLCompileOptions * compileOptions;


- (void)setCode:(id)arg1;
- (void).cxx_destruct;
- (id)code;
- (unsigned long long)type;
- (void)setType:(unsigned long long)arg1;
- (void)setCompileOptions:(id)arg1;
- (id)compileOptions;
- (id)initWithLibrary:(id)arg1 parent:(id)arg2 type:(unsigned long long)arg3 code:(id)arg4 options:(id)arg5;
- (id)newFunctionWithName:(id)arg1;

@end
