/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class MTLRenderPipelineColorAttachmentDescriptor;

@interface MTLRenderPipelineColorAttachmentDescriptorArray : NSObject  {
    MTLRenderPipelineColorAttachmentDescriptor *_descriptors[8];
}


- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (void)dealloc;
- (id)_descriptorAtIndex:(unsigned long long)arg1;

@end
