/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class NSString, <MTLFunction>, <MTLDevice>;

@interface MTLToolsComputePipelineState : MTLToolsObject <MTLComputePipelineStateSPI> {
    <MTLFunction> *_function;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) <MTLDevice> * device;
@property(readonly) unsigned long long maxTotalThreadsPerThreadgroup;
@property(readonly) unsigned long long threadExecutionWidth;
@property(readonly) unsigned long long staticLocalMemorySize;


- (id)device;
- (void).cxx_destruct;
- (unsigned long long)staticLocalMemorySize;
- (unsigned long long)threadExecutionWidth;
- (unsigned long long)maxTotalThreadsPerThreadgroup;
- (void)acceptVisitor:(id)arg1;

@end
