/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class NSString, <MTLDevice>;

@interface MTLToolsRenderPipelineState : MTLToolsObject <MTLRenderPipelineState> {
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) NSString * label;
@property(readonly) <MTLDevice> * device;


- (id)device;
- (id)label;
- (void)acceptVisitor:(id)arg1;

@end
