/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class NSPointerArray, NSObject<OS_dispatch_semaphore>;

@interface MTLToolsPointerArray : NSObject  {
    unsigned long long _pointerAdditions;
    NSPointerArray *_pointerArray;
    NSObject<OS_dispatch_semaphore> *_semaphore;
}


- (id)initWithOptions:(unsigned int)arg1;
- (void).cxx_destruct;
- (void)addPointer:(void*)arg1;
- (void)_addPointer:(void*)arg1;
- (void)removeObjectAssociatedWithBaseObject:(id)arg1;
- (void)enumeratePointersUsingBlock:(id)arg1;
- (id)objectAssociatedWithBaseObject:(id)arg1 usingBlock:(id)arg2;

@end
