/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class MTLToolsPointerArray, NSString, <MTLDevice>;

@interface MTLToolsCommandQueue : MTLToolsObject <MTLCommandQueueSPI> {
    MTLToolsPointerArray *_commandBuffers;
}

@property(readonly) MTLToolsPointerArray * commandBuffers;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(copy) NSString * label;
@property(readonly) <MTLDevice> * device;
@property int backgroundTrackingPID;
@property bool skipRender;
@property bool executionEnabled;
@property(getter=isProfilingEnabled) bool profilingEnabled;


- (id)device;
- (void)finish;
- (void).cxx_destruct;
- (void)setLabel:(id)arg1;
- (id)label;
- (void)setProfilingEnabled:(bool)arg1;
- (void)setExecutionEnabled:(bool)arg1;
- (bool)executionEnabled;
- (void)setSkipRender:(bool)arg1;
- (bool)skipRender;
- (void)setBackgroundTrackingPID:(int)arg1;
- (int)backgroundTrackingPID;
- (void)insertDebugCaptureBoundary;
- (id)commandBufferWithUnretainedReferences;
- (id)commandBuffers;
- (id)commandBuffer;
- (bool)isProfilingEnabled;
- (id)initWithBaseObject:(id)arg1 parent:(id)arg2;
- (void)acceptVisitor:(id)arg1;

@end
