/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLThreadgroupMemoryArgument : MTLArgument  {
    unsigned short _alignment;
    unsigned int _dataSize;
}


- (id)description;
- (unsigned long long)threadgroupMemoryDataSize;
- (unsigned long long)threadgroupMemoryAlignment;
- (id)initWithName:(id)arg1 type:(unsigned long long)arg2 access:(unsigned long long)arg3 isActive:(bool)arg4 locationIndex:(unsigned long long)arg5 arraySize:(unsigned long long)arg6 dataSize:(unsigned long long)arg7 alignment:(unsigned long long)arg8;
- (id)describe;

@end
