/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@class MTLVertexBufferLayoutDescriptor;

@interface MTLVertexBufferLayoutDescriptorArray : NSObject  {
    MTLVertexBufferLayoutDescriptor *_descriptors[31];
}


- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (void)dealloc;

@end
