/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@class NSString, NSMutableString;

@interface CPPDFAnnotationParserDelegate : NSObject <NSXMLParserDelegate> {
    NSMutableString *_characters;
    bool_parseError;
    struct CGPoint { 
        double x; 
        double y; 
    } _p[4];
    struct __CFArray { } *_quadPoints;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } _rect;
    struct __CFDictionary { } *_annotationDictionary;
    struct __CFString { } *_id;
    struct __CFString { } *_otherId;
    struct __CFString { } *_content;
    struct CGColor { } *_color;
}

@property(readonly) bool parseError;
@property struct __CFDictionary { }* annotationDictionary;
@property(readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } rect;
@property(readonly) struct __CFString { }* annotationId;
@property(readonly) struct __CFString { }* otherId;
@property(readonly) struct __CFString { }* content;
@property(readonly) struct CGColor { }* color;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parserDidStartDocument:(id)arg1;
- (struct __CFString { }*)otherId;
- (struct __CFString { }*)annotationId;
- (void)setAnnotationDictionary:(struct __CFDictionary { }*)arg1;
- (struct __CFDictionary { }*)annotationDictionary;
- (void)addQuadpoints;
- (bool)parseError;
- (struct __CFString { }*)content;
- (struct CGColor { }*)color;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })rect;
- (id)init;
- (void)dealloc;

@end
