/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@interface CPShapeRegion : CPGraphicRegion  {
}


- (bool)isShapeRegion;
- (void)accept:(id)arg1;

@end
