/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@interface CPTable : CPChunk <CPDisposable, CPGraphicUser> {
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } tableBounds;
    unsigned int rowCount;
    double *rowY;
    unsigned int columnCount;
    double *columnX;
    struct CGColor { } *backgroundColor;
    unsigned int backgroundGraphicCount;
    id *backgroundGraphics;
    unsigned int usedGraphicCount;
    booldisposed;
}

@property(readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } tableBounds;
@property unsigned int rowCount;
@property(readonly) double* rowY;
@property unsigned int columnCount;
@property(readonly) double* columnX;
@property(readonly) unsigned int backgroundGraphicCount;


- (void)finalize;
- (unsigned int)rowCount;
- (unsigned int)backgroundGraphicCount;
- (id)backgroundGraphicAtIndex:(unsigned int)arg1;
- (void)setBackgroundGraphics:(id)arg1;
- (void)setRowCount:(unsigned int)arg1;
- (double*)columnX;
- (double*)rowY;
- (unsigned int)usedGraphicCount;
- (void)incrementUsedGraphicCount;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })tableBounds;
- (void)dispose;
- (void)setColumnCount:(unsigned int)arg1;
- (unsigned int)columnCount;
- (struct CGColor { }*)backgroundColor;
- (void)dealloc;
- (id)initWithBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

@end
