/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@class CPZoneBorder;

@interface CPZoneBorderIntersection : NSObject <NSCopying, CPCopying> {
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } intersectionRect;
    CPZoneBorder *intersectingBorder;
    boolforwardVector;
    boolbackwardVector;
}


- (bool)forwardVector;
- (void)setBackwardVector:(bool)arg1;
- (void)setForwardVector:(bool)arg1;
- (bool)backwardVector;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })intersectionRect;
- (id)intersectingBorder;
- (long long)comparePositionLengthwise:(id)arg1;
- (void)setIntersectingBorder:(id)arg1;
- (void)setIntersectionRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initSuper;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
