/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@class NSMutableArray;

@interface RMTable : NSObject <NSFastEnumeration> {
    NSMutableArray *_matrix;
    unsigned long long _elementCount;
    NSMutableArray *_rowFirstElements;
    NSMutableArray *_columnFirstElements;
    struct CGPDFLayout { } *_layout;
    struct CGPDFNode { } *_tableRoot;
    bool_rowOrder;
}

@property(readonly) struct CGPDFPage { }* page;
@property bool rowOrder;


- (id)columnAtIndex:(unsigned long long)arg1;
- (void)matrixDealloc;
- (bool)rowOrder;
- (void)setRowOrder:(bool)arg1;
- (id)initWithRoot:(struct CGPDFNode { }*)arg1 layout:(struct CGPDFLayout { }*)arg2;
- (unsigned long long)columns;
- (struct CGPDFPage { }*)page;
- (unsigned long long)rows;
- (struct CGPDFLayout { }*)layout;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })bounds;
- (void)dealloc;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long *x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;
- (void)dump;
- (id)rowAtIndex:(unsigned long long)arg1;

@end
