/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

@interface UIPDFHighlightLayer : CALayer  {
    struct CGPath { } *_clipPath;
    struct CGPath { } *_borderPath;
    struct CGPoint { 
        double x; 
        double y; 
    } offset;
}

@property struct CGPath { }* clipPath;
@property struct CGPath { }* borderPath;
@property struct CGPoint { double x1; double x2; } offset;


- (void)setBorderPath:(struct CGPath { }*)arg1;
- (struct CGPath { }*)borderPath;
- (void)setClipPath:(struct CGPath { }*)arg1;
- (struct CGPath { }*)clipPath;
- (struct CGPoint { double x1; double x2; })offset;
- (void)setOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)dealloc;

@end
