/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreText.framework/CoreText
 */

@class NSDictionary;

@interface CTFeatureSetting : NSDictionary  {
    NSDictionary *_dictionary;
}


- (id)objectForKey:(id)arg1;
- (id)keyEnumerator;
- (bool)isEqualToDictionary:(id)arg1;
- (id)tag;
- (id)value;
- (id)selector;
- (id)type;
- (id)initWithDictionary:(id)arg1;
- (unsigned long long)count;
- (void)dealloc;
- (bool)isEqualToFeatureSetting:(id)arg1;
- (id)initWithNormalizedDictionary:(id)arg1;
- (id)initWithType:(id)arg1 selector:(id)arg2 tag:(id)arg3 value:(id)arg4;

@end
