/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@class NSFont;

@interface NSIdentityGlyphInfo : NSGlyphInfo  {
    NSFont *_font;
    unsigned int _glyph;
}

+ (id)glyphInfoWithGlyph:(unsigned int)arg1 forFont:(id)arg2 baseString:(id)arg3;
+ (void)initialize;

- (unsigned int)_glyph;
- (id)initWithGlyph:(unsigned int)arg1 forFont:(id)arg2 baseString:(id)arg3;
- (unsigned int)_glyphForFont:(id)arg1 baseString:(id)arg2;
- (id)_font;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
