/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
 */

@interface BKSProcessAssertionCreateResponseEvent : BKSProcessAssertionEvent  {
    bool_success;
}

@property bool success;


- (void)setSuccess:(bool)arg1;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (id)description;
- (bool)success;

@end
