/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/Accounts.framework/Accounts
 */

@interface ACDataclassAction : NSObject <NSSecureCoding> {
    bool_isDestructive;
    long long _type;
}

@property(readonly) long long type;
@property(readonly) bool isDestructive;

+ (id)actionWithType:(long long)arg1;
+ (bool)supportsSecureCoding;
+ (id)destructiveActionWithType:(long long)arg1;

- (bool)isDestructive;
- (long long)type;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithType:(long long)arg1 destructivity:(bool)arg2;

@end
