/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@class NSNumber, NSDictionary;

@interface IDSMessage : IDSBaseMessage <NSCopying> {
    NSNumber *_wantsDeliveryStatus;
    NSDictionary *_deliveryStatusContext;
    NSNumber *_version;
}

@property(copy) NSNumber * wantsDeliveryStatus;
@property(copy) NSDictionary * deliveryStatusContext;
@property(copy) NSNumber * version;


- (id)messageBody;
- (id)deliveryStatusContext;
- (id)wantsDeliveryStatus;
- (void)setDeliveryStatusContext:(id)arg1;
- (void)setWantsDeliveryStatus:(id)arg1;
- (id)userAgentHeaderString;
- (bool)wantsUserAgentInHeaders;
- (bool)wantsHTTPHeaders;
- (bool)wantsAPSRetries;
- (id)version;
- (void)setVersion:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (void)dealloc;

@end
