/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@class NSString;

@interface IDSSocketPairAppAckMessage : IDSSocketPairMessage  {
    unsigned long long _offset;
    unsigned int _sequenceNumber;
    unsigned short _streamID;
    NSString *_peerResponseIdentifier;
}

@property unsigned int sequenceNumber;
@property(readonly) unsigned short streamID;
@property(retain,readonly) NSString * peerResponseIdentifier;


- (id)initWithSequenceNumber:(unsigned int)arg1 streamID:(unsigned short)arg2 peerResponseIdentifier:(id)arg3;
- (id)peerResponseIdentifier;
- (id)_nonHeaderData;
- (id)initWithCommand:(unsigned char)arg1 underlyingData:(id)arg2;
- (void)setSequenceNumber:(unsigned int)arg1;
- (unsigned short)streamID;
- (void)dealloc;
- (unsigned char)command;
- (unsigned int)sequenceNumber;

@end
