/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKBrowsingContextHandle : NSObject <NSSecureCoding> {
    unsigned long long _pageID;
}

@property(getter=_pageID,readonly) unsigned long long pageID;

+ (bool)supportsSecureCoding;

- (unsigned long long)_pageID;
- (id)_initWithPageID:(unsigned long long)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
