/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class NSString, NSURLResponse, NSURL, NSURLRequest;

@interface WKNavigationData : NSObject <WKObject> {
    struct ObjectStorage<API::NavigationData> { 
        struct type { 
            unsigned char __lx[472]; 
        } data; 
    } _data;
}

@property(readonly) NSString * title;
@property(readonly) NSURLRequest * originalRequest;
@property(readonly) NSURL * destinationURL;
@property(readonly) NSURLResponse * response;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) struct Object { int (**x1)(); id x2; }* _apiObject;


- (id)originalRequest;
- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (id).cxx_construct;
- (id)response;
- (id)title;
- (void)dealloc;
- (id)destinationURL;

@end
