/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@class NSString;

@interface WKNPAPIPlugInContainer : NSObject <WKNPAPIPlugInContainer> {
    struct NetscapePlugin { } *_plugin;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)_initWithNetscapePlugin:(struct NetscapePlugin { }*)arg1;
- (bool)openPlugInPreferencePane;
- (void)_invalidate;

@end
