/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class NSString;

@interface WKNSData : NSData <WKObject> {
    struct ObjectStorage<API::Data> { 
        struct type { 
            unsigned char __lx[48]; 
        } data; 
    } _data;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) struct Object { int (**x1)(); id x2; }* _apiObject;


- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (id).cxx_construct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (const void*)bytes;
- (unsigned long long)length;
- (void)dealloc;

@end
