/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@class NSArray;

@interface WKUserContentController : NSObject  {
    struct RefPtr<WebKit::WebUserContentControllerProxy> { 
        struct WebUserContentControllerProxy {} *m_ptr; 
    } _userContentControllerProxy;
    struct RetainPtr<NSMutableArray> { 
        void *m_ptr; 
    } _userScripts;
}

@property(copy,readonly) NSArray * userScripts;


- (void)removeScriptMessageHandlerForName:(id)arg1;
- (void)addScriptMessageHandler:(id)arg1 name:(id)arg2;
- (void)removeAllUserScripts;
- (void)addUserScript:(id)arg1;
- (id)userScripts;
- (void).cxx_destruct;
- (id).cxx_construct;
- (id)init;

@end
