/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@class NSString;

@interface WKWebProcessPlugInScriptWorld : NSObject <WKObject> {
    struct ObjectStorage<WebKit::InjectedBundleScriptWorld> { 
        struct type { 
            unsigned char __lx[24]; 
        } data; 
    } _world;
}

@property(readonly) struct InjectedBundleScriptWorld { int (**x1)(); id x2; struct RefPtr<WebCore::DOMWrapperWorld> { struct DOMWrapperWorld {} *x_3_1_1; } x3; }* _scriptWorld;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) struct Object { int (**x1)(); id x2; }* _apiObject;

+ (id)world;
+ (id)normalWorld;

- (void)clearWrappers;
- (struct InjectedBundleScriptWorld { int (**x1)(); id x2; struct RefPtr<WebCore::DOMWrapperWorld> { struct DOMWrapperWorld {} *x_3_1_1; } x3; }*)_scriptWorld;
- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (id).cxx_construct;
- (void)dealloc;

@end
