/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKWebProcessBundleParameters : NSObject  {
    struct RetainPtr<NSMutableDictionary> { 
        void *m_ptr; 
    } _parameters;
}


- (void)setParameter:(id)arg1 forKey:(id)arg2;
- (void).cxx_destruct;
- (id).cxx_construct;
- (id)initWithDictionary:(id)arg1;
- (id)valueForKey:(id)arg1;

@end
