/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage;

@interface CIBlendModeFilter : CIFilter  {
    CIImage *inputImage;
    CIImage *inputBackgroundImage;
}

@property(retain) CIImage * inputImage;
@property(retain) CIImage * inputBackgroundImage;

+ (id)_filter_display_name;
+ (id)_kernel;
+ (id)customAttributes;

- (id)outputImage;
- (id)inputImage;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_extent;
- (bool)_needUnpremuls;
- (void)setInputBackgroundImage:(id)arg1;
- (id)inputBackgroundImage;
- (void)setInputImage:(id)arg1;

@end
