/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIBurstYUVImage : NSObject  {
    char *Ybuffer;
    char *Cbuffer;
    int width;
    int height;
    int bytesPerRow;
    struct __CFData { } *dataPtr;
    struct __CVBuffer { } *pixelBuffer;
    struct __IOSurface { } *ioSurf;
}

@property int width;
@property int height;
@property int bytesPerRow;
@property char * Ybuffer;
@property char * Cbuffer;


- (void)setHeight:(int)arg1;
- (void)setWidth:(int)arg1;
- (int)height;
- (int)width;
- (void)dealloc;
- (int)bytesPerRow;
- (void)setBytesPerRow:(int)arg1;
- (void)setCbuffer:(char *)arg1;
- (void)setYbuffer:(char *)arg1;
- (struct __CVBuffer { }*)pixelBuffer;
- (id)initWithCIImage:(id)arg1 ctx:(id)arg2 maxDimension:(int)arg3;
- (void)convertRGBAToYUV420:(char *)arg1 rgbaBytesPerRow:(int)arg2;
- (id)initWithIOSurface:(struct __IOSurface { }*)arg1 maxDimension:(int)arg2;
- (char *)Cbuffer;
- (char *)Ybuffer;
- (id)initWithCGImage:(struct CGImage { }*)arg1 maxDimension:(int)arg2;

@end
