/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage, CIVector;

@interface CIColorMatrix : CIFilter  {
    CIImage *inputImage;
    CIVector *inputRVector;
    CIVector *inputGVector;
    CIVector *inputBVector;
    CIVector *inputAVector;
    CIVector *inputBiasVector;
}

@property(retain) CIImage * inputImage;
@property(retain) CIVector * inputRVector;
@property(retain) CIVector * inputGVector;
@property(retain) CIVector * inputBVector;
@property(retain) CIVector * inputAVector;
@property(retain) CIVector * inputBiasVector;

+ (id)customAttributes;

- (id)outputImage;
- (void)setDefaults;
- (id)inputImage;
- (id)inputBiasVector;
- (id)inputAVector;
- (id)inputBVector;
- (id)inputGVector;
- (id)inputRVector;
- (void)setInputBiasVector:(id)arg1;
- (void)setInputAVector:(id)arg1;
- (void)setInputBVector:(id)arg1;
- (void)setInputGVector:(id)arg1;
- (void)setInputRVector:(id)arg1;
- (void)setInputImage:(id)arg1;

@end
