/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage, NSNumber;

@interface CIColorPosterize : CIFilter  {
    CIImage *inputImage;
    NSNumber *inputLevels;
}

@property(retain) CIImage * inputImage;
@property(retain) NSNumber * inputLevels;

+ (id)customAttributes;

- (id)outputImage;
- (void)setDefaults;
- (id)inputImage;
- (id)inputLevels;
- (void)setInputLevels:(id)arg1;
- (id)_kernel;
- (bool)_isIdentity;
- (void)setInputImage:(id)arg1;

@end
