/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class FCRFaceDetector, NSMutableDictionary, CIContext;

@interface CIFaceCoreDetector : CIDetector  {
    CIContext *context;
    NSMutableDictionary *featureOptions;
    FCRFaceDetector *faceCoreDetector;
}

@property(retain) CIContext * context;
@property FCRFaceDetector * faceCoreDetector;


- (void)finalize;
- (void)setContext:(id)arg1;
- (id)context;
- (void)dealloc;
- (void)setFaceCoreDetector:(id)arg1;
- (id)faceCoreDetector;
- (id)featuresInImage:(id)arg1;
- (id)initWithContext:(id)arg1 options:(id)arg2;
- (id)featuresInImage:(id)arg1 options:(id)arg2;
- (struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })ctmForImageWithBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 orientation:(int)arg2;
- (id)createFaceCoreDataFromCIImage:(id)arg1 width:(unsigned long long*)arg2 height:(unsigned long long*)arg3;
- (id)adjustedImageFromImage:(id)arg1 orientation:(int)arg2 inverseCTM:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; }*)arg3;

@end
