/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage, CIColor;

@interface CIFalseColor : CIFilter  {
    CIImage *inputImage;
    CIColor *inputColor0;
    CIColor *inputColor1;
}

@property(retain) CIImage * inputImage;
@property(retain) CIColor * inputColor0;
@property(retain) CIColor * inputColor1;

+ (id)customAttributes;

- (id)outputImage;
- (void)setDefaults;
- (id)inputImage;
- (id)inputColor1;
- (id)inputColor0;
- (void)setInputColor1:(id)arg1;
- (void)setInputColor0:(id)arg1;
- (id)_kernel;
- (void)setInputImage:(id)arg1;

@end
