/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage, NSNumber;

@interface CIFaceBalance : CIFilter <_CIFilterProperties> {
    CIImage *inputImage;
    NSNumber *inputOrigI;
    NSNumber *inputOrigQ;
    NSNumber *inputStrength;
    NSNumber *inputWarmth;
}

@property(retain) CIImage * inputImage;
@property(retain) NSNumber * inputOrigI;
@property(retain) NSNumber * inputOrigQ;
@property(retain) NSNumber * inputStrength;
@property(retain) NSNumber * inputWarmth;

+ (id)customAttributes;

- (id)outputImage;
- (id)_initFromProperties:(id)arg1;
- (id)_outputProperties;
- (void)setDefaults;
- (id)inputImage;
- (id)inputWarmth;
- (id)inputOrigQ;
- (id)inputOrigI;
- (void)setInputWarmth:(id)arg1;
- (void)setInputOrigQ:(id)arg1;
- (void)setInputOrigI:(id)arg1;
- (void)setInputStrength:(id)arg1;
- (id)inputStrength;
- (id)_kernel;
- (bool)_isIdentity;
- (void)setInputImage:(id)arg1;

@end
