/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIFourfoldReflectedTile : CITile2Filter  {
}

+ (id)customAttributes;

- (id)outputImage;
- (id)_kernel_source;
- (id)_kernel_name;

@end
