/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage;

@interface CIMaskToAlpha : CIFilter  {
    CIImage *inputImage;
}

@property(retain) CIImage * inputImage;

+ (id)customAttributes;

- (id)outputImage;
- (void)setDefaults;
- (id)inputImage;
- (id)_kernel;
- (void)setInputImage:(id)arg1;

@end
