/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage, CIVector;

@interface CITemperatureAndTint : CIFilter  {
    CIImage *inputImage;
    CIVector *inputNeutral;
    CIVector *inputTargetNeutral;
}

@property(retain) CIImage * inputImage;
@property(retain) CIVector * inputNeutral;
@property(retain) CIVector * inputTargetNeutral;

+ (id)customAttributes;

- (id)outputImage;
- (void)setDefaults;
- (id)inputImage;
- (id)inputTargetNeutral;
- (id)inputNeutral;
- (void)setInputTargetNeutral:(id)arg1;
- (void)setInputNeutral:(id)arg1;
- (void)setInputImage:(id)arg1;

@end
