/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit
 */

@class NSObject<OS_xpc_object>, NSObject<OS_dispatch_queue>;

@interface PKDaemonClient : NSObject  {
    NSObject<OS_xpc_object> *_pkd;
    NSObject<OS_dispatch_queue> *_replyQueue;
    long long _protocolVersion;
}

@property(retain) NSObject<OS_xpc_object> * pkd;
@property(retain) NSObject<OS_dispatch_queue> * replyQueue;
@property long long protocolVersion;


- (void)setReplyQueue:(id)arg1;
- (id)pkd;
- (void)releaseHold:(id)arg1 reply:(id)arg2;
- (void)holdPlugins:(id)arg1 flags:(unsigned long long)arg2 reply:(id)arg3;
- (void)bulkPlugins:(unsigned long long)arg1 reply:(id)arg2;
- (void)removePlugIns:(id)arg1 reply:(id)arg2;
- (void)addPlugIns:(id)arg1 reply:(id)arg2;
- (void)set:(id)arg1 uuids:(id)arg2;
- (id)request:(const char *)arg1;
- (void)send:(id)arg1 reply:(id)arg2;
- (id)request:(const char *)arg1 paths:(id)arg2;
- (void)setPkd:(id)arg1;
- (void)copyReceipt:(id)arg1;
- (void)setPluginAnnotations:(id)arg1 annotations:(id)arg2 reply:(id)arg3;
- (void)readyPlugIns:(id)arg1 flags:(unsigned long long)arg2 reply:(id)arg3;
- (void)accessPlugIns:(id)arg1 flags:(unsigned long long)arg2 reply:(id)arg3;
- (void)matchPlugIns:(id)arg1 flags:(unsigned long long)arg2 reply:(id)arg3;
- (id)errorInReply:(id)arg1;
- (long long)protocolVersion;
- (void)setProtocolVersion:(long long)arg1;
- (id)replyQueue;
- (id)initWithServiceName:(const char *)arg1;
- (void).cxx_destruct;

@end
