/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@class NSObject<OS_dispatch_queue>, NSMutableDictionary, NSMutableArray;

@interface __NSCFMemoryURLCache : NSObject  {
    id _internal;
    unsigned long long _memoryCapacity;
    unsigned long long _currentLength;
    NSMutableDictionary *_memoryStorage;
    NSMutableArray *_memoryStorageLRU;
    NSObject<OS_dispatch_queue> *_memoryQueue;
}

+ (void)initialize;

- (void)removeAllCachedResponses;
- (id)description;
- (void)dealloc;
- (void)storeCachedResponse:(id)arg1 forRequest:(id)arg2;
- (id)cachedResponseForRequest:(id)arg1;
- (void)setDiskCapacity:(unsigned long long)arg1;
- (void)setMemoryCapacity:(unsigned long long)arg1;
- (unsigned long long)currentMemoryUsage;
- (unsigned long long)diskCapacity;
- (unsigned long long)memoryCapacity;
- (void)removeCachedResponseForRequest:(id)arg1;
- (id)initMemoryCache;
- (id)initEmptyCache;
- (id)initWithMemoryCapacity:(unsigned long long)arg1 diskCapacity:(unsigned long long)arg2 diskPath:(id)arg3;
- (id)initByCallingSuperSuperInit;
- (unsigned long long)currentDiskUsage;

@end
