/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface __NSCFURLSessionXPC : NSObject  {
}

+ (void)initialize;
+ (id)bgSessionClientInterface;
+ (id)bgSessionInterface;
+ (id)bgSessionManagerInterface;


@end
