/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface __NSCFLocalDataTask : __NSCFLocalSessionTask  {
}


- (bool)isKindOfClass:(Class)arg1;
- (void)_onqueue_didReceiveResponse:(id)arg1 completion:(id)arg2;

@end
