/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@class NSDictionary, NSHTTPURLResponseInternal;

@interface NSHTTPURLResponse : NSURLResponse  {
    NSHTTPURLResponseInternal *_httpInternal;
}

@property(readonly) long long statusCode;
@property(copy,readonly) NSDictionary * allHeaderFields;

+ (id)localizedStringForStatusCode:(long long)arg1;
+ (bool)supportsSecureCoding;
+ (bool)isErrorStatusCode:(long long)arg1;

- (id)initWithURL:(id)arg1 statusCode:(long long)arg2 HTTPVersion:(id)arg3 headerFields:(id)arg4;
- (id)allHeaderFields;
- (long long)statusCode;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (struct __SecTrust { }*)_peerTrust;
- (void)_setPeerTrust:(struct __SecTrust { }*)arg1;
- (id)_clientCertificateState;
- (id)_clientCertificateChain;
- (id)initWithURL:(id)arg1 statusCode:(long long)arg2 headerFields:(id)arg3 requestTime:(double)arg4;
- (id)_peerCertificateChain;
- (id)_initWithCFURLResponse:(struct _CFURLResponse { }*)arg1;

@end
