/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@class NSCachedURLResponse, <NSURLProtocolClient>, NSURLRequest, NSURLProtocolInternal;

@interface NSURLProtocol : NSObject  {
    NSURLProtocolInternal *_internal;
}

@property(retain,readonly) <NSURLProtocolClient> * client;
@property(copy,readonly) NSURLRequest * request;
@property(copy,readonly) NSCachedURLResponse * cachedResponse;

+ (id)canonicalRequestForRequest:(id)arg1;
+ (bool)requestIsCacheEquivalent:(id)arg1 toRequest:(id)arg2;
+ (bool)canInitWithRequest:(id)arg1;
+ (bool)registerClass:(Class)arg1;
+ (void)removePropertyForKey:(id)arg1 inRequest:(id)arg2;
+ (void)setProperty:(id)arg1 forKey:(id)arg2 inRequest:(id)arg3;
+ (id)propertyForKey:(id)arg1 inRequest:(id)arg2;
+ (void)unregisterClass:(Class)arg1;
+ (id)canonicalRequestForRequest:(id)arg1 task:(id)arg2;
+ (bool)canInitWithTask:(id)arg1;
+ (Class)_protocolClassForRequest:(id)arg1;
+ (id)_makeRequestCanonicalByMakingRequestURLCanonical:(id)arg1;

- (id)client;
- (void)stopLoading;
- (id)request;
- (void)dealloc;
- (void)startLoading;
- (id)initWithTask:(id)arg1 cachedResponse:(id)arg2 client:(id)arg3;
- (id)cachedResponse;
- (id)initWithRequest:(id)arg1 cachedResponse:(id)arg2 client:(id)arg3;

@end
