/* Generated by RuntimeBrowser.
   Image: /usr/lib/libextension.dylib
 */

@interface _NSItemProviderTypeCoercion : NSObject  {
    id _value;
    Class _targetClass;
}

@property(retain) id value;
@property(copy) Class targetClass;

+ (id)coercionClassStringFromClass:(Class)arg1;
+ (SEL)selectorForCoercionFromValue:(id)arg1 toClass:(Class)arg2;
+ (id)typeCoercionForValue:(id)arg1 targetClass:(Class)arg2;

- (id)_NSItemProviderTypeCoercion_coercedNSFileWrapperValueFromNSDataValue:(id)arg1 error:(id*)arg2;
- (id)_NSItemProviderTypeCoercion_coercedNSFileWrapperValueFromNSURLValue:(id)arg1 error:(id*)arg2;
- (id)_NSItemProviderTypeCoercion_coercedNSDataValueFromNSURLValue:(id)arg1 error:(id*)arg2;
- (id)coerceValueAndReturnError:(id*)arg1;
- (bool)shouldCoerceForCoding;
- (Class)targetClass;
- (void)setTargetClass:(Class)arg1;
- (id)value;
- (void)setValue:(id)arg1;
- (void)dealloc;

@end
