/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class NSArray;

@interface BWMetadataObjectFormat : BWFormat  {
    NSArray *_metadataIdentifiers;
}

+ (id)formatWithMetadataIdentifiers:(id)arg1;
+ (void)initialize;

- (unsigned int)mediaType;
- (id)_initWithMetadataIdentifiers:(id)arg1;
- (id)debugDescription;
- (id)description;
- (void)dealloc;

@end
