/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class BWGraph, NSMutableDictionary;

@interface BWNodeEnumerator : NSEnumerator  {
    BWGraph *_graph;
    unsigned long long _depth;
    NSMutableDictionary *_nodeVisitCountMap;
}

+ (void)initialize;

- (id)_visitedCount:(id)arg1;
- (unsigned long long)_updateVisitedCount:(id)arg1;
- (id)initWithGraph:(id)arg1;
- (void)dealloc;

@end
