/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface BWStillImageTimeMachine : NSObject  {
    struct OpaqueFigSimpleMutex { } *_timeMachineMutex;
    struct opaqueCMSampleBuffer {} **_frames;
    bool_suspended;
    int _capacity;
}

@property(readonly) int capacity;

+ (bool)afComplete:(struct opaqueCMSampleBuffer { }*)arg1;
+ (void)initialize;

- (int)capacity;
- (struct opaqueCMSampleBuffer { }*)copyBestFrame;
- (int)insertFrame:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)suspendAndDrain;
- (void)_drain;
- (void)resume;
- (void)drain;
- (id)initWithCapacity:(int)arg1;
- (void)dealloc;

@end
