/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class BWDeviceOrientationMonitor, NSString, NSObject<OS_dispatch_queue>, NSMutableArray;

@interface BWVideoOrientationMetadataNode : BWNode <BWDeviceOrientationMonitorPortraitLandscapeUpdateDelegate> {
    int _sourcePosition;
    struct OpaqueCMClock { } *_clock;
    struct OpaqueCMClock { } *_masterClock;
    BWDeviceOrientationMonitor *_deviceOrientationMonitor;
    struct opaqueCMFormatDescription { } *_boxedMetadataFormatDescription;
    unsigned int _localIDOfOrientationMetadata;
    int _mostRecentDevicePortraitLandscapeOrientation;
    bool_recording;
    NSMutableArray *_transforms;
    struct OpaqueCMBlockBuffer {} *_bbufCache[5];
    NSObject<OS_dispatch_queue> *_emitSamplesDispatchQueue;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (void)initialize;

- (void)_renderSampleBufferForBoxedFormatOutputAtTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 orientation:(int)arg2 firstSample:(bool)arg3;
- (void)_queueUpCallToEmitSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 markerBufferOrFirstSample:(bool)arg2;
- (void)_releaseTransformData;
- (void)didUpdatePortraitLandscapeOrientation:(int)arg1;
- (void)setSourcePosition:(int)arg1;
- (int)sourcePosition;
- (void)renderSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 forInput:(id)arg2;
- (id)nodeSubType;
- (void)didReachEndOfDataForInput:(id)arg1;
- (void)configurationWithID:(long long)arg1 updatedFormat:(id)arg2 didBecomeLiveForInput:(id)arg3;
- (id)nodeType;
- (id)init;
- (void)dealloc;
- (void)setMasterClock:(struct OpaqueCMClock { }*)arg1;
- (struct OpaqueCMClock { }*)masterClock;

@end
