/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class <FigCaptureSessionPreviewTapDelegate>;

@interface FigCaptureSessionProxy : NSObject  {
    struct OpaqueFigCaptureSession { } *_session;
    long long _identifier;
    bool_previewTapOpened;
    <FigCaptureSessionPreviewTapDelegate> *_previewTapDelegate;
}

@property(readonly) long long identifier;

+ (void)initialize;

- (id)initWithFigCaptureSession:(struct OpaqueFigCaptureSession { }*)arg1 identifier:(long long)arg2;
- (void)closePreviewTap;
- (int)openPreviewTapWithDelegate:(id)arg1;
- (long long)identifier;
- (void)dealloc;

@end
