/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class FigStateMachine, FigDelegateStorage;

@interface FigCameraViewfinderStream : NSObject  {
    FigDelegateStorage *_delegateStorage;
    FigStateMachine *_stateMachine;
    struct OpaqueFigEndpoint { } *_endpoint;
    struct OpaqueFigEndpointStream { } *_stream;
    struct OpaqueFigVirtualDisplaySource { } *_displaySource;
    id _endpointsChangedNotificationToken;
    id _streamsChangedNotificationToken;
}

+ (void)initialize;

- (void)setDelegate:(id)arg1 queue:(id)arg2;
- (void)_handleStreamsChanged:(id)arg1;
- (void)_handleEndpointsChanged:(id)arg1;
- (int)enqueueVideoSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)openWithDestination:(id)arg1;
- (void)_setupStateMachine;
- (void)close;
- (id)init;
- (void)dealloc;
- (void)_setEndpoint:(struct OpaqueFigEndpoint { }*)arg1;

@end
