/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class NSString, FigCaptureSourceConfiguration, FigCaptureSinkConfiguration;

@interface FigCaptureConnectionConfiguration : NSObject <FigXPCCoding, NSCopying> {
    NSString *_connectionID;
    unsigned int _mediaType;
    FigCaptureSourceConfiguration *_sourceConfiguration;
    FigCaptureSinkConfiguration *_sinkConfiguration;
    bool_enabled;
}

@property(copy) NSString * connectionID;
@property unsigned int mediaType;
@property(retain) FigCaptureSourceConfiguration * sourceConfiguration;
@property(retain) FigCaptureSinkConfiguration * sinkConfiguration;
@property bool enabled;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (void)initialize;

- (void)setMediaType:(unsigned int)arg1;
- (unsigned int)mediaType;
- (id)copyXPCEncoding;
- (id)connectionID;
- (id)sinkConfiguration;
- (id)initWithXPCEncoding:(id)arg1;
- (bool)enabled;
- (void)setEnabled:(bool)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (bool)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setSourceConfiguration:(id)arg1;
- (id)sourceConfiguration;
- (void)setSinkConfiguration:(id)arg1;
- (void)setConnectionID:(id)arg1;

@end
