/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class NSString;

@interface FigStateMachine : NSObject  {
    id _owner;
    int _lock;
    bool_performsAtomicStateTransitions;
    unsigned int _currentState;
    struct FigStateMachineStateConfiguration { boolx1; id x2; id x3; id x4; } *_stateConfigurations;
    BOOL _stateCount;
    NSString *_label;
}

@property bool performsAtomicStateTransitions;
@property(readonly) unsigned int currentState;
@property(readonly) NSString * label;
@property(readonly) NSString * currentStateLabel;

+ (void)initialize;

- (bool)transitionToState:(unsigned int)arg1;
- (bool)performsAtomicStateTransitions;
- (bool)transitionToState:(unsigned int)arg1 fromStates:(unsigned int)arg2;
- (void)whenTransitioningToStatesFail:(unsigned int)arg1 callHandler:(id)arg2;
- (void)whenTransitioningToStates:(unsigned int)arg1 callHandler:(id)arg2;
- (void)markStateAsTerminal:(unsigned int)arg1;
- (id)labelForState:(unsigned int)arg1;
- (bool)_transitionToState:(unsigned int)arg1 fromStates:(unsigned int)arg2 errorStatus:(int)arg3;
- (void)whenTransitioningToStateFails:(unsigned int)arg1 callHandler:(id)arg2;
- (void)setPerformsAtomicStateTransitions:(bool)arg1;
- (id)currentStateLabel;
- (bool)transitionToState:(unsigned int)arg1 errorStatus:(int)arg2;
- (bool)transitionToState:(unsigned int)arg1 fromState:(unsigned int)arg2;
- (void)whenTransitioningToState:(unsigned int)arg1 callHandler:(id)arg2;
- (void)whenTransitioningFromState:(unsigned int)arg1 toState:(unsigned int)arg2 callHandler:(id)arg3;
- (void)setLabel:(id)arg1 forState:(unsigned int)arg2;
- (id)initWithLabel:(id)arg1 stateCount:(BOOL)arg2 initialState:(unsigned int)arg3 owner:(id)arg4;
- (id)label;
- (unsigned int)currentState;
- (id)description;
- (void)dealloc;

@end
