/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@class NSMutableDictionary, NSMutableArray;

@interface MSVCLICommandInterpreter : NSObject  {
    NSMutableDictionary *_commandToInvocationsMap;
    NSMutableArray *_retainedBlockHandlers;
}


- (bool)executeWithArgumentCount:(int)arg1 arguments:(const char **)arg2;
- (void)addHandlerToCommand:(id)arg1 withBlock:(id)arg2;
- (void)addHandlerToCommand:(id)arg1 withTarget:(id)arg2 action:(SEL)arg3;
- (void).cxx_destruct;
- (id)init;

@end
