/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@class NSURL, NSObject<OS_dispatch_group>, NSError;

@interface MSVImageResizeOperation : NSOperation  {
    bool_overwriteExistingDestination;
    NSURL *_sourceURL;
    NSURL *_destinationURL;
    NSObject<OS_dispatch_group> *_operationGroup;
    NSError *_error;
    struct CGSize { 
        double width; 
        double height; 
    } _destinationSize;
}

@property(readonly) NSURL * sourceURL;
@property(readonly) struct CGSize { double x1; double x2; } destinationSize;
@property(readonly) NSURL * destinationURL;
@property(readonly) bool overwriteExistingDestination;
@property(readonly) NSObject<OS_dispatch_group> * operationGroup;
@property(readonly) NSError * error;


- (id)error;
- (bool)overwriteExistingDestination;
- (struct CGSize { double x1; double x2; })destinationSize;
- (id)initWithSourceURL:(id)arg1 destinationSize:(struct CGSize { double x1; double x2; })arg2 destinationURL:(id)arg3 overwriteExistingDestination:(bool)arg4;
- (void).cxx_destruct;
- (void)main;
- (id)operationGroup;
- (id)sourceURL;
- (id)destinationURL;

@end
