/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@class NSUUID, NSString;

@interface MSVXPCTransaction : NSObject  {
    NSUUID *_identifier;
    NSString *_name;
}

@property(readonly) NSString * name;
@property(getter=isActive,readonly) bool active;

+ (id)activeTransactions;

- (void)endTransactionOnDate:(id)arg1;
- (void)endTransaction;
- (void)beginTransaction;
- (id)initWithName:(id)arg1;
- (void).cxx_destruct;
- (id)_identifier;
- (id)name;
- (bool)isActive;
- (id)description;
- (void)dealloc;

@end
