/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSSetM : NSMutableSet  {
    unsigned int _used : 58;
    unsigned long long _size;
    unsigned long long _mutations;
    id *_objs;
}

+ (bool)automaticallyNotifiesObserversForKey:(id)arg1;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)__new:(const id*)arg1 :(unsigned long long)arg2 :(bool)arg3;

- (void)finalize;
- (id)member:(id)arg1;
- (void)enumerateObjectsWithOptions:(unsigned long long)arg1 usingBlock:(id)arg2;
- (id)objectEnumerator;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)removeAllObjects;
- (void)addObject:(id)arg1;
- (unsigned long long)count;
- (void)removeObject:(id)arg1;
- (void)dealloc;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long *x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;
- (double)clumpingInterestingThreshold;
- (double)clumpingFactor;
- (void)getObjects:(id*)arg1 count:(unsigned long long)arg2;
- (void)_mutate;

@end
