/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSCFType : NSObject  {
}

+ (bool)automaticallyNotifiesObserversForKey:(id)arg1;

- (void)finalize;
- (oneway void)release;
- (bool)_isDeallocating;
- (bool)_tryRetain;
- (id)description;
- (unsigned long long)hash;
- (unsigned long long)retainCount;
- (bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)retain;

@end
