/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@class NSObject<OS_dispatch_source>;

@interface _CFPrefsSynchronizer : NSObject  {
    NSObject<OS_dispatch_source> *_synchTimer;
    struct __CFSet { } *_dirtySources;
    struct _opaque_pthread_mutex_t { 
        long long __sig; 
        BOOL __opaque[56]; 
    } _CFPrefsDirtySourcesLock;
    bool_active;
}

+ (id)sharedInstance;

- (void)clear;
- (void)synchronize;
- (id)init;
- (void)synchronizeAndWait;
- (void)noteDirtySource:(id)arg1;
- (void)disableTimer_alreadyLocked;
- (void)clear_alreadyLocked;
- (void)enableTimer_alreadyLocked;

@end
