/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface NSDate : NSObject <NSCopying, NSSecureCoding> {
}

@property(readonly) double timeIntervalSinceReferenceDate;

+ (id)dateWithTimeInterval:(double)arg1 sinceDate:(id)arg2;
+ (id)dateWithTimeIntervalSince1970:(double)arg1;
+ (id)dateWithTimeIntervalSinceReferenceDate:(double)arg1;
+ (bool)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)distantPast;
+ (id)dateWithTimeIntervalSinceNow:(double)arg1;
+ (id)date;
+ (id)distantFuture;
+ (double)timeIntervalSinceReferenceDate;
+ (id)dateWithString:(id)arg1;
+ (id)dateWithDate:(id)arg1;
+ (id)dateWithNaturalLanguageString:(id)arg1 locale:(id)arg2;
+ (id)dateWithNaturalLanguageString:(id)arg1;
+ (id)dateWithNaturalLanguageString:(id)arg1 date:(id)arg2 locale:(id)arg3;
+ (id)dateForDaysSince1970:(int)arg1;
+ (int)daysSince1970;

- (id)initWithTimeIntervalSince1970:(double)arg1;
- (id)descriptionWithLocale:(id)arg1;
- (double)timeIntervalSince1970;
- (id)initWithTimeIntervalSinceReferenceDate:(double)arg1;
- (double)timeIntervalSinceNow;
- (id)initWithTimeInterval:(double)arg1 sinceDate:(id)arg2;
- (id)dateByAddingTimeInterval:(double)arg1;
- (id)earlierDate:(id)arg1;
- (id)laterDate:(id)arg1;
- (bool)isEqualToDate:(id)arg1;
- (long long)compare:(id)arg1;
- (id)initWithString:(id)arg1;
- (id)initWithTimeIntervalSinceNow:(double)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)timeIntervalSinceDate:(id)arg1;
- (double)timeIntervalSinceReferenceDate;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (long long)compare:(id)arg1 toUnitGranularity:(unsigned long long)arg2;
- (bool)isEqual:(id)arg1 toUnitGranularity:(unsigned long long)arg2;
- (bool)isInSameDayAsDate:(id)arg1;
- (bool)isInYesterday;
- (bool)isInTomorrow;
- (bool)isInToday;
- (id)addTimeInterval:(double)arg1;
- (id)initWithDate:(id)arg1;
- (unsigned long long)_cfTypeID;
- (bool)isNSDate__;
- (id)dateWithCalendarFormat:(id)arg1 timeZone:(id)arg2;
- (id)descriptionWithCalendarFormat:(id)arg1 timeZone:(id)arg2 locale:(id)arg3;
- (Class)classForCoder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (bool)_web_isToday;
- (id)_web_RFC1123DateString;
- (long long)_web_compareDay:(id)arg1;
- (id)replacementObjectForPortCoder:(id)arg1;
- (int)daysSince1970;
- (bool)isBeforeDate:(id)arg1;
- (bool)isAfterDate:(id)arg1;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;

@end
