/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@class NSString, NSData;

@interface NSTimeZone : NSObject <NSCopying, NSSecureCoding> {
}

@property(copy,readonly) NSString * name;
@property(copy,readonly) NSData * data;

+ (id)timeZoneForSecondsFromGMT:(long long)arg1;
+ (id)timeZoneWithAbbreviation:(id)arg1;
+ (id)timeZoneWithName:(id)arg1;
+ (id)systemTimeZone;
+ (id)localTimeZone;
+ (id)defaultTimeZone;
+ (bool)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (void)resetSystemTimeZone;
+ (id)timeZoneWithName:(id)arg1 data:(id)arg2;
+ (id)timeZoneDataVersion;
+ (void)setAbbreviationDictionary:(id)arg1;
+ (id)knownTimeZoneNames;
+ (void)setDefaultTimeZone:(id)arg1;
+ (id)abbreviationDictionary;

- (long long)secondsFromGMT;
- (bool)isDaylightSavingTime;
- (id)abbreviation;
- (id)initWithName:(id)arg1;
- (long long)secondsFromGMTForDate:(id)arg1;
- (id)nextDaylightSavingTimeTransitionAfterDate:(id)arg1;
- (id)name;
- (id)data;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)nextDaylightSavingTimeTransition;
- (double)daylightSavingTimeOffset;
- (bool)isEqualToTimeZone:(id)arg1;
- (id)initWithName:(id)arg1 data:(id)arg2;
- (id)localizedName:(long long)arg1 locale:(id)arg2;
- (bool)isDaylightSavingTimeForDate:(id)arg1;
- (id)abbreviationForDate:(id)arg1;
- (double)daylightSavingTimeOffsetForDate:(id)arg1;
- (bool)isNSTimeZone__;
- (unsigned long long)_cfTypeID;
- (Class)classForCoder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)replacementObjectForPortCoder:(id)arg1;

@end
