/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AddressBook.framework/AddressBook
 */

@class NSString, NSConditionLock, <ABPredicateDelegate>, DAContactsSearchQuery, DADConnection, NSMutableArray;

@interface ABServerSearchPredicate : ABPredicate <DASearchQueryConsumer> {
    void *_source;
    NSString *_accountIdentifier;
    NSString *_searchString;
    bool_includeSourceInResults;
    DADConnection *_connection;
    DAContactsSearchQuery *_searchQuery;
    NSMutableArray *_searchResults;
    NSConditionLock *_doneLock;
    int _error;
    <ABPredicateDelegate> *_delegate;
    bool_includePhotosInResults;
}

@property void* source;
@property(copy) NSString * accountIdentifier;
@property(copy) NSString * searchString;
@property bool includeSourceInResults;
@property bool includePhotosInResults;
@property <ABPredicateDelegate> * delegate;
@property(readonly) int error;
@property(retain) DADConnection * connection;


- (int)error;
- (void)searchQuery:(id)arg1 finishedWithError:(id)arg2;
- (void)searchQuery:(id)arg1 returnedResults:(id)arg2;
- (id)accountIdentifier;
- (void)setSearchString:(id)arg1;
- (void)setConnection:(id)arg1;
- (id)connection;
- (void)setSource:(void*)arg1;
- (void*)source;
- (id)searchString;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void)setAccountIdentifier:(id)arg1;
- (bool)includeSourceInResults;
- (id)initWithSearchString:(id)arg1 source:(void*)arg2 account:(id)arg3;
- (int)_errorForDAStatusCode:(long long)arg1;
- (void)_searchQueryIsDone;
- (void)runPredicateWithDelegate:(id)arg1;
- (void)runPredicate;
- (bool)includePhotosInResults;
- (id)initWithSearchString:(id)arg1 source:(void*)arg2 account:(id)arg3 includeSourceInResults:(bool)arg4;
- (void)setIncludePhotosInResults:(bool)arg1;
- (void)setIncludeSourceInResults:(bool)arg1;
- (void)ab_runPredicateWithSortOrder:(unsigned int)arg1 inAddressBook:(void*)arg2 withDelegate:(id)arg3;
- (id)initWithSearchString:(id)arg1 source:(void*)arg2 account:(id)arg3 includeSourceInResults:(bool)arg4 includePhotosInResults:(bool)arg5;

@end
