/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AddressBook.framework/AddressBook
 */

@interface ABTCC : NSObject  {
    bool_calledExternalChangeCallbacks;
    long long _simulateType;
    bool_simulateAccessPrompt;
    bool_simulateAccessPromptGranted;
    unsigned int _simulateAccessPromptDelay;
}

+ (id)sharedInstance;

- (id)init;
- (void)dealloc;
- (void)simulateIfAccessPromptDisplayedThenUserGrantedAccess:(bool)arg1 withDelay:(unsigned int)arg2;
- (void)simulate:(long long)arg1;
- (void)accessRequestWithCompletion:(id)arg1;
- (unsigned char)isAccessRestricted;
- (int)accessPreflight;
- (id)_simulateQueue;
- (void)callExternalChangeCallbacks:(bool)arg1;

@end
