/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSManagedObjectContext;

@interface _PFManagedObjectReferenceQueue : NSObject  {
    int _cd_rc;
    int _spinLock;
    int _flags;
    int _signalRunloop;
    NSManagedObjectContext *_context;
    struct __CFArray { } *_queue;
    struct __CFRunLoopObserver { } *_rlObserver;
}


- (void)finalize;
- (oneway void)release;
- (bool)_signal;
- (bool)_isDeallocating;
- (bool)_tryRetain;
- (unsigned long long)retainCount;
- (void)dealloc;
- (id)retain;
- (bool)_queueBatchForDealloc:(struct __CFArray { }*)arg1;
- (long long)_queueCount;
- (id)initForContext:(id)arg1;
- (void)_contextDidDealloc;
- (void)_unregisterRunloopObservers;
- (void)_processReferenceQueue:(bool)arg1;
- (bool)_GC_queueForDealloc:(id)arg1;
- (bool)_queueForDealloc:(id)arg1;

@end
