/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface _PFWeakReference : NSObject  {
    id _object;
    unsigned long long _objectAddress;
}

@property(readonly) id object;

+ (id)weakReferenceWithObject:(id)arg1;

- (id)initWithObject:(id)arg1;
- (id)object;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;

@end
