/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSString, NSDictionary, NSData, NSExpression, NSMutableArray, NSArray;

@interface NSEntityMapping : NSObject  {
    void *_reserved;
    void *_reserved1;
    NSDictionary *_mappingsByName;
    NSString *_name;
    unsigned long long _mappingType;
    NSString *_sourceEntityName;
    NSData *_sourceEntityVersionHash;
    NSString *_destinationEntityName;
    NSData *_destinationEntityVersionHash;
    NSExpression *_sourceExpression;
    NSDictionary *_userInfo;
    NSString *_entityMigrationPolicyClassName;
    NSMutableArray *_attributeMappings;
    NSMutableArray *_relationshipMappings;
    struct __entityMappingFlags { 
        unsigned int _isInUse : 1; 
        unsigned int _reservedEntityMapping : 31; 
    } _entityMappingFlags;
}

@property(copy) NSString * name;
@property unsigned long long mappingType;
@property(copy) NSString * sourceEntityName;
@property(copy) NSData * sourceEntityVersionHash;
@property(copy) NSString * destinationEntityName;
@property(copy) NSData * destinationEntityVersionHash;
@property(retain) NSArray * attributeMappings;
@property(retain) NSArray * relationshipMappings;
@property(retain) NSExpression * sourceExpression;
@property(retain) NSDictionary * userInfo;
@property(copy) NSString * entityMigrationPolicyClassName;

+ (void)initialize;

- (id)userInfo;
- (id)name;
- (void)setName:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setUserInfo:(id)arg1;
- (id)description;
- (bool)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)setEntityMigrationPolicyClassName:(id)arg1;
- (id)relationshipMappings;
- (id)attributeMappings;
- (id)entityMigrationPolicyClassName;
- (id)sourceExpression;
- (id)destinationEntityVersionHash;
- (id)sourceEntityVersionHash;
- (void)setMappingType:(unsigned long long)arg1;
- (void)setDestinationEntityVersionHash:(id)arg1;
- (void)setDestinationEntityName:(id)arg1;
- (void)setSourceEntityVersionHash:(id)arg1;
- (void)setSourceEntityName:(id)arg1;
- (void)setRelationshipMappings:(id)arg1;
- (void)setAttributeMappings:(id)arg1;
- (void)setSourceExpression:(id)arg1;
- (id)destinationEntityName;
- (id)sourceEntityName;
- (unsigned long long)mappingType;
- (bool)isEditable;
- (bool)_hasInferredMappingNeedingValidation;
- (void)_addRelationshipMapping:(id)arg1;
- (void)_addAttributeMapping:(id)arg1;
- (id)_migrationPolicy;
- (id)_mappingsByName;
- (id)_initWithSourceEntityDescription:(id)arg1 destinationEntityDescription:(id)arg2;
- (void)_setIsEditable:(bool)arg1;
- (void)_createCachesAndOptimizeState;
- (void)_throwIfNotEditable;

@end
