/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSSQLEntity, NSMutableArray, NSString;

@interface NSSQLStatement : NSObject  {
    NSSQLEntity *_entity;
    NSMutableArray *_bindVariables;
    NSMutableArray *_bindIntarrays;
    NSString *_sqlString;
    bool_isImpossibleCondition;
    NSSQLEntity *_fakeEntityForFetch;
}


- (void)clearCaches;
- (id)entity;
- (bool)isReadOnly;
- (id)description;
- (void)dealloc;
- (void)removeAllBindIntarrays;
- (unsigned int)addBindIntarray:(id)arg1;
- (void)setBindIntarrays:(id)arg1;
- (void)cacheFakeEntityForFetch:(id)arg1;
- (void)setBindVariables:(id)arg1;
- (id)bindVariables;
- (void)removeAllBindVariables;
- (id)fakeEntityForFetch;
- (bool)isImpossibleCondition;
- (id)bindIntarrays;
- (void)setSQLString:(id)arg1;
- (id)initWithEntity:(id)arg1 sqlString:(id)arg2;
- (id)initWithEntity:(id)arg1;
- (id)sqlString;
- (void)setImpossibleCondition:(bool)arg1;
- (unsigned int)addBindVariable:(id)arg1;

@end
