/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSAttributeDescription;

@interface NSSQLBindVariable : NSObject  {
    int _cd_rc;
    id _value;
    unsigned int _sqlType;
    unsigned int _index;
    long long _int64;
    NSAttributeDescription *_attributeDescription;
}


- (oneway void)release;
- (void)setIndex:(unsigned int)arg1;
- (unsigned int)index;
- (bool)_isDeallocating;
- (bool)_tryRetain;
- (id)value;
- (void)setValue:(id)arg1;
- (unsigned long long)retainCount;
- (void)dealloc;
- (id)retain;
- (bool)hasObjectValue;
- (unsigned int)unsignedInt;
- (long long)int64;
- (void)setUnsignedInt:(unsigned int)arg1;
- (void)setInt64:(long long)arg1;
- (id)attributeDescription;
- (id)initWithUnsignedInt:(unsigned int)arg1 sqlType:(unsigned int)arg2;
- (id)initWithValue:(id)arg1 sqlType:(unsigned int)arg2 attributeDescription:(id)arg3;
- (id)initWithInt64:(long long)arg1 sqlType:(unsigned int)arg2;
- (unsigned int)sqlType;

@end
