/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSSQLToMany : NSSQLRelationship  {
}


- (bool)isToMany;
- (id)initWithEntity:(id)arg1 propertyDescription:(id)arg2;
- (id)inverseToOne;

@end
