/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSString;

@interface PFUbiquityFileCoordinator : NSFileCoordinator  {
    NSString *_localPeerID;
}

@property(readonly) NSString * localPeerID;

+ (id)newFileCoordinatorForUbiquityRootLocation:(id)arg1;
+ (id)newFileCoordinatorForUbiquityRootLocation:(id)arg1 andLocalPeerID:(id)arg2;
+ (id)newFileCoordinatorForUbiquitousExternalDataReferenceLocation:(id)arg1;

- (id)initWithFilePresenter:(id)arg1;
- (void)dealloc;
- (bool)shouldRetryForError:(id)arg1 ignoreFile:(bool*)arg2;
- (void)coordinateReadingItemAtLocation:(id)arg1 options:(unsigned long long)arg2 retryOnError:(bool)arg3 error:(id*)arg4 byAccessor:(id)arg5;
- (id)localPeerID;

@end
