/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSString, NSMutableDictionary, NSArray, NSDate;

@interface PFUbiquitySaveSnapshot : NSObject  {
    NSDate *_transactionDate;
    NSString *_modelVersionHash;
    NSString *_exportingPeerID;
    NSString *_localPeerID;
    NSMutableDictionary *_storeNameToStoreSaveSnapshots;
}

@property(retain) NSDate * transactionDate;
@property(readonly) NSString * modelVersionHash;
@property(readonly) NSString * exportingPeerID;
@property(readonly) NSArray * storeNames;
@property(readonly) NSString * localPeerID;


- (id)description;
- (void)dealloc;
- (id)initWithTransactionLog:(id)arg1;
- (id)storeSaveSnapshotForStore:(id)arg1;
- (id)storeNames;
- (id)initWithSaveNotification:(id)arg1 withLocalPeerID:(id)arg2;
- (void)setTransactionDate:(id)arg1;
- (id)transactionDate;
- (id)storeSaveSnapshotForStoreName:(id)arg1;
- (id)exportingPeerID;
- (id)localPeerID;
- (id)modelVersionHash;

@end
