/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSString, PFUbiquityPeer, NSNumber, PFUbiquityStoreMetadata;

@interface PFUbiquityPeerRange : NSManagedObject  {
}

@property(retain) NSNumber * peerStart;
@property(retain) NSNumber * end;
@property(retain) NSNumber * peerEnd;
@property(retain) NSString * peerEntityName;
@property(retain) NSNumber * start;
@property(retain) PFUbiquityPeer * peer;
@property(retain) PFUbiquityStoreMetadata * storeMetadata;


- (void)loadFromBaselineDictionary:(id)arg1;

@end
