/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSString, NSMutableSet;

@interface PFUbiquityToManyConflictDiff : NSObject  {
    NSMutableSet *_insertedObjectIDs;
    NSMutableSet *_deletedObjectIDs;
    NSString *_relationshipKey;
}

@property(readonly) NSMutableSet * insertedObjectIDs;
@property(readonly) NSMutableSet * deletedObjectIDs;
@property(readonly) NSString * relationshipKey;


- (id)description;
- (bool)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)relationshipKey;
- (void)diffWithLogSnapshot:(id)arg1 andPreviousSnapshot:(id)arg2;
- (id)initForRelationshipAtKey:(id)arg1;
- (id)deletedObjectIDs;
- (id)insertedObjectIDs;

@end
