/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSString;

@interface PFZipEndOfCentralDirectoryRecord : NSObject  {
    unsigned short _numberOfDisk;
    unsigned short _diskWhereCentralDirectoryStarts;
    unsigned short _numberOfCentralDirectoryRecordsOnThisDisk;
    unsigned short _totalNumberOfCentralDirectoryRecords;
    unsigned int _byteSizeOfCentralDirectory;
    unsigned int _centralDirectoryOffset;
    unsigned short _commentLength;
    NSString *_comment;
}

@property unsigned short numberOfDisk;
@property unsigned short diskWhereCentralDirectoryStarts;
@property unsigned short numberOfCentralDirectoryRecordsOnThisDisk;
@property unsigned short totalNumberOfCentralDirectoryRecords;
@property unsigned int byteSizeOfCentralDirectory;
@property unsigned int centralDirectoryOffset;
@property(readonly) unsigned short commentLength;
@property(retain) NSString * comment;


- (id)comment;
- (void)setComment:(id)arg1;
- (id)description;
- (id)init;
- (void)dealloc;
- (unsigned short)commentLength;
- (void)setCentralDirectoryOffset:(unsigned int)arg1;
- (unsigned int)centralDirectoryOffset;
- (void)setByteSizeOfCentralDirectory:(unsigned int)arg1;
- (unsigned int)byteSizeOfCentralDirectory;
- (void)setTotalNumberOfCentralDirectoryRecords:(unsigned short)arg1;
- (unsigned short)totalNumberOfCentralDirectoryRecords;
- (void)setNumberOfCentralDirectoryRecordsOnThisDisk:(unsigned short)arg1;
- (unsigned short)numberOfCentralDirectoryRecordsOnThisDisk;
- (void)setDiskWhereCentralDirectoryStarts:(unsigned short)arg1;
- (unsigned short)diskWhereCentralDirectoryStarts;
- (void)setNumberOfDisk:(unsigned short)arg1;
- (unsigned short)numberOfDisk;
- (void)appendToData:(id)arg1;
- (unsigned long long)loadFromData:(id)arg1 offset:(unsigned long long)arg2;
- (unsigned long long)loadFromBytes:(const char *)arg1 offset:(unsigned long long)arg2;

@end
