/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@class NSDictionary, NSURL, NSObject<DDActionDelegate>;

@interface DDAction : NSObject <NSCoding, NSSecureCoding> {
    struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; } *_result;
    struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; } *_coalescedResult;
    struct __CFArray { } *_associatedResults;
    NSDictionary *_context;
    NSURL *_url;
    bool_cachedCoalescedResult;
    bool_cachedAssociatedResults;
    bool_isDefaultAction;
    id _delegate;
}

@property bool isDefaultAction;
@property NSObject<DDActionDelegate> * delegate;

+ (bool)isAvailable;
+ (id)defaultActionWithURL:(id)arg1 result:(struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)arg2 context:(id)arg3;
+ (id)actionWithURL:(id)arg1 result:(struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)arg2 context:(id)arg3;
+ (bool)supportsSecureCoding;

- (bool)isDefaultAction;
- (void)_copyURL:(id)arg1;
- (void)_copyURL:(id)arg1 andString:(id)arg2;
- (id)initWithURL:(id)arg1 result:(struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)arg2 context:(id)arg3;
- (struct __CFArray { }*)associatedResults;
- (struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)coalescedResult;
- (void)prepareViewControllerForActionController:(id)arg1;
- (void)setIsDefaultAction:(bool)arg1;
- (void)addToRecents;
- (struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)result;
- (int)interactionType;
- (bool)hasUserInterface;
- (void)perform;
- (id)viewController;
- (id)localizedName;
- (id)context;
- (id)url;
- (id)delegate;
- (id)description;
- (void)setDelegate:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
