/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDCallAction : DDTelephoneNumberAction  {
}

+ (bool)isAvailable;

- (bool)_titleFitsInActionSheet:(id)arg1;
- (bool)_retrieveNameForDestinationNumber:(id*)arg1 label:(id*)arg2;
- (id)_nameForPerson:(void*)arg1;
- (id)_UIDsAndLabelsMatchingPhoneNumber:(id)arg1 inAddressBook:(void*)arg2;
- (int)interactionType;
- (void)perform;
- (id)localizedName;

@end
