/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@class NSString;

@interface DDCreateEventAction : DDAction <EKEventEditViewDelegate> {
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)prepareViewControllerForActionController:(id)arg1;
- (int)interactionType;
- (id)localizedName;
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(int)arg2;

@end
