/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@class NSMapTable, NSString, NSOperationQueue, NSObject<OS_dispatch_queue>, DDActionController, NSObject<DDDetectionControllerDelegate>;

@interface DDDetectionController : NSObject <UIActionSheetDelegate> {
    NSOperationQueue *_fullScannerQueue;
    NSOperationQueue *_urlScannerQueue;
    NSObject<OS_dispatch_queue> *_protectQueue;
    NSMapTable *_containerToOperationsTable;
    NSMapTable *_containerToResultsTable;
    NSMapTable *_containerToContextsTable;
    DDActionController *_actionController;
    NSObject<DDDetectionControllerDelegate> *_delegate;
}

@property NSObject<DDDetectionControllerDelegate> * delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (bool)_shouldConsiderResultForCoreRecents:(struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)arg1;
+ (id)tapAndHoldSchemes;
+ (id)sharedController;

- (void)_enqueueOperation:(id)arg1;
- (bool)_shouldImmediatelyShowActionSheetForURL:(id)arg1;
- (bool)_shouldImmediatelyShowActionSheetForCoreResult:(struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)arg1;
- (struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)_resultForURL:(id)arg1 forContainer:(id)arg2 context:(id*)arg3;
- (void)performAction:(id)arg1 inView:(id)arg2 interactionDelegate:(id)arg3;
- (void)containerWillBeRemoved:(id)arg1;
- (void)_commonResetResultsForContainer:(id)arg1;
- (void)setContext:(id)arg1 forContainer:(id)arg2;
- (void)setResults:(struct __CFArray { }*)arg1 forContainer:(id)arg2;
- (struct __DDResult { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __DDQueryRange { struct __DDQueryOffset { long long x_1_2_1; long long x_1_2_2; } x_2_1_1; struct __DDQueryOffset { long long x_2_2_1; long long x_2_2_2; } x_2_1_2; } x2; struct { long long x_3_1_1; long long x_3_1_2; } x3; long long x4; struct __CFArray {} *x5; struct __CFString {} *x6; struct __CFString {} *x7; void *x8; void *x9; }*)_resultForIdentifier:(id)arg1 forContainer:(id)arg2 context:(id*)arg3;
- (void)_doURLification:(id)arg1;
- (void)startURLificationForContainer:(id)arg1 detectedTypes:(unsigned long long)arg2 options:(int)arg3;
- (void)_startCoalescedURLification:(id)arg1;
- (id)_newOperationForContainer:(id)arg1;
- (void)_startCoalescedURLification:(id)arg1 clearPreviousResults:(bool)arg2;
- (void)_resetStoredResultsForContainer:(id)arg1;
- (void)resetResultsForContainer:(id)arg1;
- (void)startURLificationForContainer:(id)arg1 detectedTypes:(unsigned long long)arg2;
- (void)cancelURLificationForContainer:(id)arg1;
- (void)performAction:(id)arg1 inView:(id)arg2 withPopoverController:(id)arg3 interactionDelegate:(id)arg4;
- (void)performAction:(id)arg1 fromAlertController:(id)arg2 interactionDelegate:(id)arg3;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)actionsForURL:(id)arg1;
- (struct __DDResult { }*)resultForDOMNode:(id)arg1 forFrame:(id)arg2;
- (id)defaultActionForAnchor:(id)arg1 url:(id)arg2 forFrame:(id)arg3;
- (struct __DDResult { }*)resultForNode:(id)arg1 url:(id)arg2 frame:(id)arg3 contextRef:(id*)arg4;
- (struct __DDResult { }*)_resultForAnchor:(id)arg1 forFrame:(id)arg2 context:(id*)arg3;
- (id)actionsForAnchor:(id)arg1 url:(id)arg2 forFrame:(id)arg3;
- (id)defaultActionForDOMNode:(id)arg1 forFrame:(id)arg2;
- (bool)shouldImmediatelyShowActionSheetForURL:(id)arg1 forFrame:(id)arg2;
- (id)actionsForDOMNode:(id)arg1 forFrame:(id)arg2;
- (void)resetResultsForFrame:(id)arg1;
- (void)startURLificationForFrame:(id)arg1 detectedTypes:(unsigned long long)arg2;
- (void)cancelURLificationForFrame:(id)arg1;
- (void)frameWillBeRemoved:(id)arg1;
- (void)setContext:(id)arg1 forFrame:(id)arg2;
- (void)setResults:(struct __CFArray { }*)arg1 forFrame:(id)arg2;
- (void)startURLificationForFrame:(id)arg1 detectedTypes:(unsigned long long)arg2 options:(int)arg3;
- (struct __DDResult { }*)resultForLinkAtIndex:(unsigned long long)arg1 inTextStorage:(id)arg2;
- (id)_applyBlock:(id)arg1 withResultsAtIndex:(unsigned long long)arg2 ofStorage:(id)arg3 context:(id)arg4;
- (id)_resultForLinkAtIndex:(unsigned long long)arg1 inTextStorage:(id)arg2 subResult:(id*)arg3 url:(id*)arg4;
- (id)_subResultAtIndex:(unsigned long long)arg1 ofResult:(id)arg2;
- (void)resetResultsForTextView:(id)arg1;
- (id)defaultActionAtIndex:(unsigned long long)arg1 ofStorage:(id)arg2 context:(id)arg3;
- (id)actionsAtIndex:(unsigned long long)arg1 ofStorage:(id)arg2 context:(id)arg3;
- (bool)shouldImmediatelyShowActionSheetForTapAtIndex:(unsigned long long)arg1 ofStorage:(id)arg2;

@end
