/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP
 */

@class NSArray;

@interface MFIMAPMessage : MFMailMessage  {
    unsigned long long _size;
    NSArray *_customFlags;
    unsigned int _uid;
    unsigned long long _uniqueRemoteId;
}


- (id)remoteMailboxURL;
- (id)mailboxName;
- (void)setHasTemporaryUid:(bool)arg1;
- (void)setIsPartial:(bool)arg1;
- (bool)isPartial;
- (void)setUniqueRemoteId:(unsigned long long)arg1;
- (unsigned long long)uniqueRemoteId;
- (id)originalMailboxURL;
- (id)remoteID;
- (bool)hasTemporaryUid;
- (id)messageID;
- (unsigned long long)messageSize;
- (void)setPreferredEncoding:(unsigned int)arg1;
- (bool)isMessageContentsLocallyAvailable;
- (id)customFlags;
- (long long)compareByNumberWithMessage:(id)arg1;
- (id)initWithFlags:(unsigned long long)arg1 customFlags:(id)arg2 size:(unsigned long long)arg3 uid:(unsigned int)arg4;
- (unsigned int)uid;
- (id)description;
- (void)dealloc;
- (void)setUid:(unsigned int)arg1;

@end
