/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP
 */

@class CastleIMAPAccount;

@interface MFNewcastleSMTPAccount : SMTPAccount  {
    CastleIMAPAccount *_castleAccount;
}

@property(retain) CastleIMAPAccount * castleAccount;

+ (id)accountTypeIdentifier;

- (id)displayHostname;
- (id)mailAccountIfAvailable;
- (bool)shouldUseAuthentication;
- (void)setCastleAccount:(id)arg1;
- (id)castleAccount;
- (void)dealloc;

@end
