/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP
 */

@interface MobileMeAccount : iToolsAccount  {
}

+ (id)hostname;
+ (id)defaultPathNameForAccountWithHostname:(id)arg1 username:(id)arg2;
+ (id)displayedAccountTypeString;
+ (id)deliveryHostName;
+ (id)emailAddressHostPart;
+ (void)initialize;

- (bool)isHostnameEquivalentTo:(id)arg1;
- (bool)isAccountClassEquivalentTo:(id)arg1;
- (bool)shouldFetchACEDBInfoForError:(id)arg1;

@end
