/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebDeviceOrientationProviderMockInternal : NSObject  {
    struct OwnPtr<WebCore::DeviceOrientationClientMock> { 
        struct DeviceOrientationClientMock {} *m_ptr; 
    } m_core;
}


- (id)lastOrientation;
- (void)startUpdating;
- (void)stopUpdating;
- (void).cxx_destruct;
- (void)setController:(struct DeviceOrientationController { }*)arg1;
- (id).cxx_construct;
- (void)setOrientation:(id)arg1;
- (id)init;

@end
