/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@class NSTimer, NSString, NSArray, WebPluginController, WebEvent, WebDataSource, WAKView;

@interface WebHTMLViewPrivate : NSObject  {
    boolclosed;
    boolignoringMouseDraggedEvents;
    boolprinting;
    boolpaginateScreenContent;
    WAKView *layerHostingView;
    booldrawingIntoLayer;
    WebEvent *mouseDownEvent;
    boolhandlingMouseDownEvent;
    WebEvent *keyDownEvent;
    boolexposeInputContext;
    struct CGPoint { 
        double x; 
        double y; 
    } lastScrollPosition;
    boolinScrollPositionChanged;
    WebPluginController *pluginController;
    NSString *toolTip;
    id trackingRectOwner;
    void *trackingRectUserData;
    NSTimer *autoscrollTimer;
    WebEvent *autoscrollTriggerEvent;
    NSArray *pageRects;
    booltransparentBackground;
    struct WebHTMLViewInterpretKeyEventsParameters { struct KeyboardEvent {} *x1; boolx2; boolx3; boolx4; boolx5; } *interpretKeyEventsParameters;
    WebDataSource *dataSource;
    SEL selectorForDoCommandBySelector;
}

+ (void)initialize;

- (void)finalize;
- (void)clear;
- (id).cxx_construct;
- (void)dealloc;

@end
