/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCARCHacks : NSObject  {
}

+ (id)performSelector:(SEL)arg1 withReturnedObjectOnClass:(Class)arg2 withObject:(id)arg3;
+ (void)performSelector:(SEL)arg1 onClass:(Class)arg2 withObject:(id)arg3;


@end
