/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCDeviceCapabilities : NSObject  {
    bool_supportsBlockLevelEncryption;
    bool_supportsFileLevelEncryption;
}

@property(readonly) bool supportsBlockLevelEncryption;
@property(readonly) bool supportsFileLevelEncryption;

+ (id)currentDevice;

- (bool)supportsFileLevelEncryption;
- (bool)supportsBlockLevelEncryption;
- (bool)validateCapabilitiesRequiredByRestrictions:(id)arg1 localizedIncompatibilityMessage:(id)arg2 outError:(id*)arg3;
- (bool)_mediaDiskIsEncrypted;
- (id)init;

@end
