/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@class NSNumber;

@interface MCPasswordPolicyPayload : MCPayload  {
    NSNumber *_isSimplePasscodeAllowed;
    NSNumber *_isPasscodeRequired;
    NSNumber *_isAlphanumericPasscodeRequired;
    NSNumber *_isManualFetchingWhenRoaming;
    NSNumber *_minLength;
    NSNumber *_maxFailedAttempts;
    NSNumber *_maxGracePeriodMinutes;
    NSNumber *_maxInactivityMinutes;
    NSNumber *_maxPasscodeAgeDays;
    NSNumber *_passcodeHistoryCount;
    NSNumber *_minComplexCharacters;
}

@property(retain,readonly) NSNumber * isSimplePasscodeAllowed;
@property(retain,readonly) NSNumber * isPasscodeRequired;
@property(retain,readonly) NSNumber * isAlphanumericPasscodeRequired;
@property(retain,readonly) NSNumber * isManualFetchingWhenRoaming;
@property(retain,readonly) NSNumber * minLength;
@property(retain,readonly) NSNumber * maxFailedAttempts;
@property(retain,readonly) NSNumber * maxGracePeriodMinutes;
@property(retain,readonly) NSNumber * maxInactivityMinutes;
@property(retain,readonly) NSNumber * maxPasscodeAgeDays;
@property(retain,readonly) NSNumber * passcodeHistoryCount;
@property(retain,readonly) NSNumber * minComplexCharacters;

+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
+ (id)typeStrings;

- (id)isManualFetchingWhenRoaming;
- (id)passcodeHistoryCount;
- (id)maxPasscodeAgeDays;
- (id)maxInactivityMinutes;
- (id)maxGracePeriodMinutes;
- (id)maxFailedAttempts;
- (id)isPasscodeRequired;
- (id)minComplexCharacters;
- (id)isAlphanumericPasscodeRequired;
- (id)isSimplePasscodeAllowed;
- (id)payloadDescriptionKeyValueSections;
- (id)subtitle1Description;
- (id)stubDictionary;
- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id*)arg3;
- (id)restrictions;
- (id)minLength;
- (void).cxx_destruct;
- (id)title;
- (id)description;

@end
