/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCPasscodeManager : NSObject  {
}

+ (id)sharedManager;
+ (int)unlockScreenTypeForPasscodeCharacteristics:(id)arg1;
+ (id)generateSalt;
+ (id)hashForPasscode:(id)arg1 usingMethod:(int)arg2 salt:(id)arg3;
+ (id)deviceLockedError;
+ (bool)_passcodeCharacteristics:(id)arg1 compliesWithPolicyFromRestrictions:(id)arg2 outError:(id*)arg3;
+ (id)characteristicsDictionaryFromPasscode:(id)arg1;
+ (bool)passcode:(id)arg1 compliesWithPolicyFromRestrictions:(id)arg2 checkHistory:(bool)arg3 outError:(id*)arg4;
+ (bool)isDeviceUnlocked;
+ (int)unlockScreenTypeForRestrictions:(id)arg1;
+ (id)localizedDescriptionOfPasscodePolicyFromRestrictions:(id)arg1;

- (bool)isCurrentPasscodeCompliantOutError:(id*)arg1;
- (id)localizedDescriptionOfPasscodePolicy;
- (id)_passcodeCharacteristics;
- (bool)_checkPasscode:(id)arg1 againstHistoryWithRestrictions:(id)arg2 outError:(id*)arg3;
- (id)_publicPasscodeDict;
- (id)_privatePasscodeDict;
- (id)_wrongPasscodeError;
- (void)lockDevice;
- (int)newPasscodeEntryScreenType;
- (int)currentUnlockScreenType;
- (void)passcodeExpiryDateCompletionBlock:(id)arg1;
- (bool)passcode:(id)arg1 compliesWithPolicyCheckHistory:(bool)arg2 outError:(id*)arg3;
- (bool)isPasscodeSet;
- (void)lockDeviceImmediately:(bool)arg1;
- (bool)currentPasscodeCompliesWithPolicyFromRestrictions:(id)arg1 outError:(id*)arg2;
- (bool)isDeviceLocked;
- (bool)unlockDeviceWithPasscode:(id)arg1 outError:(id*)arg2;
- (id)passcodeExpiryDateOutError:(id*)arg1;

@end
