/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CAMediaTimingFunction : NSObject <NSCoding> {
    struct CAMediaTimingFunctionPrivate { float x1[2]; float x2[2]; } *_priv;
}

+ (id)functionWithName:(id)arg1;
+ (id)functionWithControlPoints:(float)arg1 :(float)arg2 :(float)arg3 :(float)arg4;
+ (void)CAMLParserEndElement:(id)arg1 content:(id)arg2;
+ (id)uiFunctionWithControlPoints:(const struct CGPoint { double x1; double x2; }*)arg1;
+ (id)_kbTimingFunction;

- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)getControlPointAtIndex:(unsigned long long)arg1 values:(float[2])arg2;
- (void)_getPoints:(double*)arg1;
- (id)initWithControlPoints:(float)arg1 :(float)arg2 :(float)arg3 :(float)arg4;
- (float)_solveForInput:(float)arg1;
- (id)CAMLType;
- (void)encodeWithCAMLWriter:(id)arg1;

@end
