/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@class NSURL, NSError;

@interface CAMLParser : NSObject  {
    struct _CAMLParserData { } *_data;
}

@property(retain) NSURL * baseURL;
@property id delegate;
@property(readonly) NSError * error;
@property(readonly) id result;

+ (id)parseContentsOfURL:(id)arg1;
+ (id)parser;

- (bool)parseData:(id)arg1;
- (id)error;
- (void)setBaseURL:(id)arg1;
- (id)result;
- (id)baseURL;
- (id)delegate;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)didFailToLoadResourceFromURL:(id)arg1;
- (bool)parseString:(id)arg1;
- (bool)parseBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (bool)parseContentsOfURL:(id)arg1;
- (void)didLoadResource:(id)arg1 fromURL:(id)arg2;
- (id)willLoadResourceFromURL:(id)arg1;
- (void)parserWarning:(id)arg1;
- (id)elementValue;
- (void)parserError:(id)arg1;
- (id)attributeForKey:(id)arg1 remove:(bool)arg2;
- (id)objectById:(id)arg1;
- (void)setElementValue:(id)arg1;

@end
