/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UITraitCollection;

@interface _UIAttributeTraitStorageRecord : NSObject <NSCoding> {
    UITraitCollection *_traitCollection;
    id _value;
}

@property(readonly) UITraitCollection * traitCollection;
@property(readonly) id value;


- (id)initWithTraitCollection:(id)arg1 value:(id)arg2;
- (id)value;
- (id)traitCollection;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
