/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface _UIAutologgingDeallocSentinel : NSObject  {
    bool_called;
    NSString *_message;
}

@property(retain) NSString * message;
@property bool called;


- (void)setCalled:(bool)arg1;
- (bool)called;
- (void)setMessage:(id)arg1;
- (id)message;
- (void)dealloc;

@end
