/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIActionSheetExternalBackgroundView : UIView  {
}


- (void)setMaskImage:(id)arg1;
- (void)layoutSubviews;

@end
