/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString, NSURL;

@interface _UIDocumentStorage : NSObject  {
    NSString *_scope;
    NSURL *_rootURL;
}

@property(readonly) NSURL * rootURL;
@property(getter=isUbiquitous,readonly) bool ubiquitous;


- (id)rootURL;
- (bool)isUbiquitous;
- (id)initWithSearchScope:(id)arg1 rootURL:(id)arg2;
- (void)dealloc;

@end
