/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString, NSExtension, NSArray;

@interface _UIDocumentPickerDescriptor : NSObject  {
    NSExtension *_extension;
}

@property(copy,readonly) NSString * identifier;
@property(copy,readonly) NSString * localizedName;
@property(copy,readonly) NSArray * supportedContentTypes;
@property bool enabled;
@property(retain) NSExtension * extension;
@property(copy,readonly) NSString * nonUIIdentifier;
@property(retain,readonly) NSString * fileProviderDocumentGroup;

+ (BOOL)cloudEnabledStatus;
+ (void)setCloudEnabledStatus:(BOOL)arg1;
+ (id)descriptorWithIdentifier:(id)arg1;
+ (id)defaultPickerIdentifierForMode:(unsigned long long)arg1 documentTypes:(id)arg2;
+ (void)setHostBundleID:(id)arg1;
+ (id)enabledPickersForMode:(unsigned long long)arg1 documentTypes:(id)arg2;
+ (id)allPickersForMode:(unsigned long long)arg1 documentTypes:(id)arg2;
+ (id)allPickers;
+ (id)hostBundleID;

- (id)imageWithScale:(double)arg1;
- (id)nonUIIdentifier;
- (id)fileProviderDocumentGroup;
- (id)nonUIBundle;
- (id)_parentApp;
- (id)_ownBundle;
- (id)_extensionValueOfClass:(Class)arg1 forKey:(id)arg2;
- (bool)supportsPickerMode:(unsigned long long)arg1;
- (bool)enabled;
- (long long)compare:(id)arg1;
- (id)extension;
- (id)supportedContentTypes;
- (id)localizedName;
- (void)setExtension:(id)arg1;
- (void)setEnabled:(bool)arg1;
- (id)identifier;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
