/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIImage, _UILegibilitySettings;

@interface _UILegibilityCachedShadow : NSObject  {
    _UILegibilitySettings *_settings;
    double _strength;
    UIImage *_shadow;
}

@property(retain) _UILegibilitySettings * settings;
@property double strength;
@property(retain) UIImage * shadow;


- (void)setShadow:(id)arg1;
- (id)shadow;
- (void)setStrength:(double)arg1;
- (bool)matchesSettings:(id)arg1 strength:(double)arg2;
- (double)strength;
- (void)setSettings:(id)arg1;
- (id)settings;
- (bool)isEqual:(id)arg1;
- (void)dealloc;

@end
