/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSMapTable;

@interface _UILazyMapTable : NSObject  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _mappingBlock;

    NSMapTable *_keysToClientTables;
    NSMapTable *_keysToValues;
    NSMapTable *_valuesToKeys;
}


- (id)objectForKey:(id)arg1;
- (id)keyEnumerable;
- (id)keys;
- (id)cachedObjects;
- (void)unregisterClient:(id)arg1 ofObjectForKey:(id)arg2;
- (bool)hasCachedObjectForKey:(id)arg1;
- (void)registerClient:(id)arg1 ofObjectForKey:(id)arg2;
- (id)cachedObjectEnumerable;
- (id)initWithMappingBlock:(id)arg1;
- (id)description;
- (unsigned long long)count;
- (void)dealloc;

@end
