/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSData;

@interface _UIMappedBitmapImage : UIImage  {
    NSData *_data;
}

@property(retain) NSData * data;

+ (void)initialize;
+ (bool)supportsSecureCoding;

- (void)_preheatBitmapData;
- (void)setData:(id)arg1;
- (id)data;
- (void)_configureImage:(id)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;

@end
