/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class _UIBackdropView, UITableView;

@interface _UIModalItemActionSheetContentView : _UIModalItemContentView  {
    UITableView *_otherButtonTableView;
    UITableView *_cancelTableView;
    _UIBackdropView *_effectView;
}


- (void)_moveAllSubviewsToEffectContentView;
- (double)numberOfOtherButtonTitles;
- (void)_createOtherButtonTableView;
- (void)_prepareViewIfNeeded;
- (void)layout;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)dealloc;

@end
