/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIObjectPerScreen : NSObject  {
}

+ (void)screenDisconnected:(id)arg1;
+ (void)removeObjectsOfClass:(Class)arg1;
+ (id)objectOfClass:(Class)arg1 forScreen:(id)arg2 withOptions:(id)arg3 createIfNecessary:(bool)arg4;
+ (void)removeObject:(id)arg1;


@end
