/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIOldSliderAnimation : UIAnimation  {
    float _startValue;
    float _endValue;
    bool_sendAction;
}


- (void)setProgress:(float)arg1;

@end
