/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface _UIPickerViewTestParameters : NSObject  {
    NSString *_testName;
    long long _remainingIterations;
    long long _rowsToScroll;
    long long _componentToScroll;
}



@end
