/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface _UIStateRestorationKeyedArchiverDelegate : NSObject <NSKeyedArchiverDelegate> {
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)sharedDelegate;

- (id)archiver:(id)arg1 willEncodeObject:(id)arg2;

@end
