/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIStoryboard;

@interface _UIStoryboardProxy : NSObject  {
    UIStoryboard *_storyboard;
}


- (id)initWithStoryboard:(id)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
