/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UISnapshotWindow : UIWindow  {
}

+ (bool)_isSystemWindow;

- (bool)_isSettingFirstResponder;
- (bool)_canBecomeKeyWindow;
- (void)_setFirstResponder:(id)arg1;

@end
