/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITiltMotionEffect : UIMotionEffect  {
    double _maximumHorizontalTiltAngle;
    double _maximumVerticalTiltAngle;
    double _rotatingSphereRadius;
}

@property double maximumHorizontalTiltAngle;
@property double maximumVerticalTiltAngle;
@property double rotatingSphereRadius;


- (double)rotatingSphereRadius;
- (void)setMaximumVerticalTiltAngle:(double)arg1;
- (double)maximumVerticalTiltAngle;
- (void)setMaximumHorizontalTiltAngle:(double)arg1;
- (double)maximumHorizontalTiltAngle;
- (void)setRotatingSphereRadius:(double)arg1;
- (id)keyPathsAndRelativeValuesForViewerOffset:(struct UIOffset { double x1; double x2; })arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
