/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITextAttachmentPlaceholderView : UIView  {
}


- (id)initWithData:(id)arg1 ofType:(id)arg2;
- (void)dealloc;

@end
