/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface _UIViewBlockVisitor : _UIViewVisitor  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _visitorBlock;

}

@property(copy) id visitorBlock;


- (id)visitorBlock;
- (void)setVisitorBlock:(id)arg1;
- (bool)_visitView:(id)arg1;
- (id)initWithTraversalDirection:(unsigned long long)arg1 visitorBlock:(id)arg2;
- (void)dealloc;

@end
