/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIViewFittingSizeTargetInfo : NSObject <NSCopying> {
    float _horizontalPriority;
    float _verticalPriority;
    struct CGSize { 
        double width; 
        double height; 
    } _targetSize;
}

@property(readonly) struct CGSize { double x1; double x2; } targetSize;
@property(readonly) float horizontalPriority;
@property(readonly) float verticalPriority;


- (id)initWithTargetSize:(struct CGSize { double x1; double x2; })arg1 horizontalPriority:(float)arg2 verticalPriority:(float)arg3;
- (bool)isEqualToTargetInfo:(id)arg1;
- (struct CGSize { double x1; double x2; })targetSize;
- (float)verticalPriority;
- (float)horizontalPriority;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
