/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSMutableDictionary, NSMutableArray;

@interface _UIWebFormDelegateEditedFormsMap : NSObject  {
    NSMutableDictionary *_map;
    NSMutableArray *_lifetimeHelper;
}


- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)_keyForWebFrame:(id)arg1;
- (id)allValues;
- (void)removeObjectForKey:(id)arg1;
- (void)removeAllObjects;
- (id)init;
- (void)dealloc;

@end
