/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIImageView, UIImage;

@interface UIAlertButton : UIButton  {
    double _imageOffset;
    bool_isNewStyle;
    UIImageView *_highlightView;
}

@property double imageOffset;
@property(readonly) UIImageView * highlightView;
@property(retain) UIImage * highlightImage;
@property bool isNewStyle;


- (bool)isNewStyle;
- (void)setImageOffset:(double)arg1;
- (double)imageOffset;
- (void)setIsNewStyle:(bool)arg1;
- (id)highlightImage;
- (void)setHighlightImage:(id)arg1;
- (void)_transitionHighlightViewToHighlighted:(bool)arg1;
- (id)highlightView;
- (void)setHighlighted:(bool)arg1;
- (id)initWithTitle:(id)arg1;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (bool)_isFocusableElement;
- (void)_focusStateDidChange;
- (void)setEnabled:(bool)arg1;
- (id)image;
- (id)title;
- (void)setTitle:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;

@end
