/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UICollectionViewFlowLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext  {
    struct { 
        unsigned int invalidateDelegateMetrics : 1; 
        unsigned int invalidateAttributes : 1; 
    } _flowLayoutInvalidationFlags;
}

@property bool invalidateFlowLayoutDelegateMetrics;
@property bool invalidateFlowLayoutAttributes;


- (bool)invalidateFlowLayoutDelegateMetrics;
- (void)setInvalidateFlowLayoutDelegateMetrics:(bool)arg1;
- (bool)invalidateFlowLayoutAttributes;
- (void)setInvalidateFlowLayoutAttributes:(bool)arg1;
- (id)init;

@end
