/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIControlTargetAction : NSObject  {
    id _target;
    SEL _action;
    int _eventMask;
    bool_cancelled;
}

@property bool cancelled;


- (void)setCancelled:(bool)arg1;
- (bool)cancelled;

@end
