/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIInputViewSetPlacement : NSObject  {
}

@property(readonly) bool showsInputViews;
@property(readonly) bool showsKeyboard;
@property(readonly) bool isUndocked;
@property(readonly) bool isInteractive;

+ (id)placement;

- (bool)accessoryViewWillAppear;
- (unsigned long long)notificationsForTransitionToPlacement:(id)arg1;
- (id)verticalConstraintForInputViewSet:(id)arg1 hostView:(id)arg2 containerView:(id)arg3;
- (id)horizontalConstraintForInputViewSet:(id)arg1 hostView:(id)arg2 containerView:(id)arg3;
- (bool)showsKeyboard;
- (bool)isUndocked;
- (bool)inputViewWillAppear;
- (bool)showsInputViews;
- (bool)isInteractive;
- (bool)isEqual:(id)arg1;

@end
