/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory10Key_Portrait : UIKBRenderFactory10Key  {
}


- (void)setupLayoutSegments;
- (id)muttitapReverseKeyImageName;
- (id)multitapCompleteKeyImageName;
- (double)controlColumnWidthFactor;
- (struct CGPoint { double x1; double x2; })globeKeyTextOffset;
- (struct CGPoint { double x1; double x2; })dictationKeyTextOffset;

@end
