/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSMutableDictionary;

@interface UIKeyboardSliceStore : NSObject  {
    NSMutableDictionary *_store;
}

+ (void)archiveSet:(id)arg1;
+ (id)sliceSetIDForKeyplaneName:(id)arg1 type:(long long)arg2 orientation:(long long)arg3;
+ (id)sliceSetForID:(id)arg1;
+ (id)sharedStore;

- (void)addSet:(id)arg1;
- (id)sliceSetForID:(id)arg1;
- (id)init;
- (void)dealloc;

@end
