/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSExtension;

@interface UIKeyboardExtensionInputMode : UIKeyboardInputMode  {
    NSExtension *_extension;
}

@property(retain) NSExtension * extension;


- (id)containingBundleDisplayName;
- (id)extendedDisplayName;
- (id)normalizedIdentifierLevels;
- (id)containingBundle;
- (id)displayName;
- (id)initWithIdentifier:(id)arg1;
- (bool)isDesiredForTraits:(id)arg1 forceASCIICapable:(bool)arg2;
- (bool)defaultLayoutIsASCIICapable;
- (bool)isAllowedForTraits:(id)arg1;
- (bool)isDefaultRightToLeft;
- (bool)isExtensionInputMode;
- (id)identifierWithLayouts;
- (id)extension;
- (void)setExtension:(id)arg1;
- (id)hardwareLayout;
- (void)dealloc;

@end
