/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardDictationMenu : UIKeyboardMenuView  {
}

+ (id)activeInstance;
+ (id)sharedInstance;

- (void)cleanupForFadeOrHide;
- (bool)centerPopUpOverKey;
- (void)performShowAnimation;
- (bool)usesDimmingView;
- (struct CGSize { double x1; double x2; })preferredSize;
- (bool)usesTable;
- (void)fade;
- (void)fadeWithDelay:(double)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)show;
- (void)hide;

@end
