/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardCandidateBarLayoutAttributes : UICollectionViewLayoutAttributes <NSCopying> {
    bool_beginsFirstPage;
    bool_endsLastPage;
}

@property bool beginsFirstPage;
@property bool endsLastPage;


- (bool)endsLastPage;
- (bool)beginsFirstPage;
- (void)setEndsLastPage:(bool)arg1;
- (void)setBeginsFirstPage:(bool)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
