/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIKeyboardPredictiveSettings : _UISettings  {
    int _lastVolume;
    bool_nextPage;
    NSString *_currentInputMode;
    bool_currentInputModeEnablePrediction;
    bool_didShowHUD;
    bool_alwaysShowTypedText;
    int _minLetters;
}

@property int minLetters;
@property bool alwaysShowTypedText;
@property int messageCount;

+ (id)sharedInstance;
+ (void)hideViaNotification;
+ (void)loadSettings;

- (void)previous;
- (id)settingsHUDConfiguration;
- (void)show:(bool)arg1;
- (void)show;
- (void)next;
- (void)cancel;
- (void)saveSettings;
- (void)setMessageCount:(int)arg1;
- (void)setAlwaysShowTypedText:(bool)arg1;
- (int)messageCount;
- (bool)alwaysShowTypedText;
- (int)minLetters;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setMinLetters:(int)arg1;
- (bool)_isShowingHUD;
- (id)_sharedHUD;
- (void)hide;
- (id)initWithDefaultValues;
- (id)valueForKey:(id)arg1;
- (void)pressRingerButton;

@end
