/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIImageView, UILabel;

@interface UIKeyboardEmojiSplitCategoryCell : UITableViewCell  {
    UIImageView *_symbol;
    UILabel *_title;
}

@property(retain) UIImageView * symbol;
@property(retain) UILabel * title;


- (void)setSymbol:(id)arg1;
- (id)symbolFont;
- (id)titleFont;
- (void)setTitleText:(id)arg1;
- (id)symbol;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end
