/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class MFMessageComposeViewController;

@interface UIMessageActivity : UIActivity  {
    bool_sourceIsManaged;
    MFMessageComposeViewController *_messageComposeViewController;
}

@property bool sourceIsManaged;
@property(retain) MFMessageComposeViewController * messageComposeViewController;

+ (long long)activityCategory;

- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (id)messageComposeViewController;
- (void)setMessageComposeViewController:(id)arg1;
- (void)prepareWithActivityItems:(id)arg1;
- (void)setSourceIsManaged:(bool)arg1;
- (id)activityViewController;
- (bool)sourceIsManaged;
- (bool)canPerformWithActivityItems:(id)arg1;
- (id)_activitySettingsImage;
- (id)_activityImage;
- (id)activityTitle;
- (id)activityType;
- (void)_cleanup;
- (void)dealloc;

@end
