/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIMutableUserNotificationCategory : UIUserNotificationCategory  {
}

@property(copy) NSString * identifier;


- (void)setActions:(id)arg1 forContext:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
