/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIMutableIndexPath : NSIndexPath  {
    unsigned long long *_mutableIndexes;
    bool_locked;
}

+ (void)setIndex:(unsigned long long)arg1 atPosition:(unsigned long long)arg2 forIndexPath:(id*)arg3;

- (void)getIndexes:(unsigned long long*)arg1;
- (id)initWithIndexes:(const unsigned long long*)arg1 length:(unsigned long long)arg2;
- (long long)compare:(id)arg1;
- (unsigned long long)indexAtPosition:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)dealloc;
- (id)retain;

@end
