/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIView;

@interface UIPickerTableViewWrapperCell : UIPickerTableViewCell  {
    UIView *_wrappedView;
    UIView *_wrappedViewContainer;
    struct CGSize { 
        double width; 
        double height; 
    } _wrappedViewSize;
}

@property(retain) UIView * wrappedView;


- (id)_anyDateLabel;
- (void)_updateWrappedView;
- (void)_updateWrappedViewFrame;
- (void)_setIsCenterCell:(bool)arg1 shouldModifyAlphaOfView:(bool)arg2;
- (void)prepareForReuse;
- (void)resizeSubviewsWithOldSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setWrappedView:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)wrappedView;
- (void)dealloc;

@end
