/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIProgressIndicator : UIActivityIndicatorView  {
}

@property int progressIndicatorStyle;

+ (struct CGSize { double x1; double x2; })size;

- (void)startAnimation;
- (int)progressIndicatorStyle;
- (void)setProgressIndicatorStyle:(int)arg1;
- (void)setAnimating:(bool)arg1;
- (void)stopAnimation;
- (void)setStyle:(int)arg1;

@end
