/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UILabel;

@interface UIPrintingMessageView : UIView  {
    UILabel *_title;
    UILabel *_message;
}


- (id)initInView:(id)arg1 title:(id)arg2;
- (void)setMessage:(id)arg1;
- (void)dealloc;

@end
