/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIPrintInfo : NSObject <NSCopying, NSCoding> {
    NSString *_printerID;
    NSString *_jobName;
    long long _outputType;
    long long _orientation;
    long long _duplex;
    long long _copies;
    bool_scaleUp;
}

@property(copy) NSString * printerID;
@property(copy) NSString * jobName;
@property long long outputType;
@property long long orientation;
@property long long duplex;
@property bool scaleUp;
@property long long copies;

+ (id)printInfoWithDictionary:(id)arg1;
+ (id)printInfo;

- (void)setScaleUp:(bool)arg1;
- (bool)scaleUp;
- (void)setCopies:(long long)arg1;
- (long long)copies;
- (void)setDuplex:(long long)arg1;
- (long long)duplex;
- (long long)outputType;
- (id)jobName;
- (id)printerID;
- (id)_createPrintSettingsForPrinter:(id)arg1;
- (void)_updateWithPrinter:(id)arg1;
- (void)setPrinterID:(id)arg1;
- (id)_initWithDictionary:(id)arg1;
- (void)setOutputType:(long long)arg1;
- (void)setJobName:(id)arg1;
- (id)dictionaryRepresentation;
- (void)setOrientation:(long long)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (long long)orientation;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
