/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIActivityIndicatorView;

@interface UIPrintStatusJobTableViewCell : UITableViewCell  {
    UIActivityIndicatorView *_activityIndicator;
}

@property bool showActive;


- (void)setShowActive:(bool)arg1;
- (bool)showActive;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;

@end
