/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface UIPrintActivityWrapperNavigationController : UINavigationController  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _completionHandler;

    bool_presentedPrintInteractionController;
}

@property bool presentedPrintInteractionController;


- (id)initWithCompletion:(id)arg1;
- (void)setPresentedPrintInteractionController:(bool)arg1;
- (bool)presentedPrintInteractionController;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)dealloc;

@end
