/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIFont, NSString, UIColor, NSAttributedString;

@interface UISimpleTextPrintFormatter : UIPrintFormatter  {
}

@property(copy) NSString * text;
@property(copy) NSAttributedString * attributedText;
@property(retain) UIFont * font;
@property(retain) UIColor * color;
@property long long textAlignment;


- (id)initWithAttributedText:(id)arg1;
- (id)initWithText:(id)arg1;

@end
