/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIStatusBarBatteryPercentItemView : UIStatusBarItemView  {
    NSString *_percentString;
}


- (bool)animatesDataChange;
- (double)extraRightPadding;
- (long long)textStyle;
- (id)contentsImage;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;
- (long long)textAlignment;
- (void)dealloc;

@end
