/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarQuietModeItemView : UIStatusBarIndicatorItemView  {
    bool_hideForAction;
    bool_registeredForNotifications;
    bool_inactive;
}


- (double)_visibleAlpha;
- (void)_triggerAction:(id)arg1;
- (void)setVisible:(bool)arg1 frame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 duration:(double)arg3;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;
- (void)setVisible:(bool)arg1;
- (void)animationDidStop:(id)arg1 finished:(bool)arg2;
- (void)dealloc;

@end
