/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIStoryboardShowSegueTemplate : UIStoryboardSegueTemplate  {
    NSString *_action;
}

@property(copy) NSString * action;


- (id)defaultSegueClassName;
- (id)segueWithDestinationViewController:(id)arg1;
- (void)setAction:(id)arg1;
- (id)action;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
