/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIStatusBarStyleRequest, UIStatusBarForegroundStyleAttributes;

@interface UIStatusBarStyleAttributes : NSObject  {
    UIStatusBarStyleRequest *_request;
    UIStatusBarForegroundStyleAttributes *_foregroundStyle;
}


- (long long)tapButtonType;
- (double)glowAnimationDuration;
- (double)foregroundAlpha;
- (id)backgroundImageName;
- (bool)areTopCornersRounded;
- (int)cornerStyle;
- (bool)supportsRasterization;
- (bool)usesVerticalLayout;
- (id)newForegroundStyleWithHeight:(double)arg1;
- (id)backgroundColorWithTintColor:(id)arg1;
- (bool)shouldUseVisualAltitude;
- (bool)isTransparent;
- (long long)legibilityStyle;
- (id)initWithRequest:(id)arg1;
- (double)heightForMetrics:(long long)arg1;
- (bool)shouldShowInternalItemType:(int)arg1 withScreenCapabilities:(id)arg2;
- (long long)idiom;
- (id)foregroundStyle;
- (bool)isDoubleHeight;
- (long long)style;
- (double)heightForOrientation:(long long)arg1;
- (bool)isTranslucent;
- (id)init;
- (void)dealloc;

@end
