/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class MKStarkCompassView;

@interface UIStatusBarMapsCompassItemView : UIStatusBarItemView  {
    MKStarkCompassView *_compassView;
}


- (double)updateContentsAndWidth;
- (void)dealloc;

@end
