/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString, NSArray, UIView;

@interface UITableViewSection : NSObject <NSCoding> {
    NSString *_headerTitle;
    UIView *_headerView;
    NSString *_footerTitle;
    UIView *_footerView;
    NSArray *_rows;
}

@property(copy) NSString * headerTitle;
@property(retain) UIView * headerView;
@property(copy) NSString * footerTitle;
@property(retain) UIView * footerView;
@property(copy) NSArray * rows;

+ (id)sectionWithRows:(id)arg1;

- (void)setFooterView:(id)arg1;
- (id)footerView;
- (void)setFooterTitle:(id)arg1;
- (id)footerTitle;
- (void)setHeaderTitle:(id)arg1;
- (id)headerTitle;
- (void)setRows:(id)arg1;
- (id)rows;
- (void)setHeaderView:(id)arg1;
- (id)headerView;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end
