/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSData;

@interface UITextCheckerDictionaryEntry : NSObject  {
    struct __CFSet { } *dictionary;
    NSData *data;
    long long size;
}


- (void)dealloc;

@end
