/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextFieldCenteredLabel : UITextFieldLabel  {
    double _textXPosition;
    double _textWidth;
}

@property double textXPosition;
@property double textWidth;


- (double)textWidth;
- (double)textXPosition;
- (void)setTextWidth:(double)arg1;
- (void)setTextXPosition:(double)arg1;
- (bool)_isTextFieldCenteredLabel;

@end
