/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIResponder<UITextInput>;

@interface UIVariableDelayLoupeGesture : UILongPressGestureRecognizer  {
    UIResponder<UITextInput> *_textView;
}

@property UIResponder<UITextInput> * textView;


- (bool)isCloseToCaret;
- (id)textView;
- (void)startTimer;
- (void)setTextView:(id)arg1;
- (void)invalidate;

@end
