/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIWebDateTimePopoverViewController;

@interface UIWebDefaultDateTimePopover : UIWebFormRotatingAccessoryPopover <UIWebFormControl> {
    UIWebDateTimePopoverViewController *_webDateTimeViewController;
}

@property(retain) UIWebDateTimePopoverViewController * _webDateTimeViewController;


- (id)_webDateTimeViewController;
- (void)set_webDateTimeViewController:(id)arg1;
- (id)initWithDOMHTMLInputElement:(id)arg1 datePickerMode:(long long)arg2;
- (void)clear:(id)arg1;
- (void)controlEndEditing;
- (void)controlBeginEditing;
- (id)controlView;
- (void)dealloc;

@end
