/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/MobileAsset.framework/MobileAsset
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString, NSDictionary, NSURL;

@interface ASAsset : NSObject  {
    NSString *_assetType;
    NSDictionary *_attributes;
    NSDictionary *_downloadOptions;
    NSString *_clientName;
    NSString *_identifier;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _progressHandler;

    struct __MobileAsset { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __CFString {} *x2; struct __CFDictionary {} *x3; struct __MobileAssetQuery {} *x4; struct __MobileAssetQuery {} *x5; unsigned char x6; } *_cfAsset;
}

@property(retain) NSString * clientName;
@property(readonly) NSDictionary * fullAttributes;
@property(readonly) NSString * assetType;
@property(readonly) NSDictionary * attributes;
@property(readonly) long long state;
@property(readonly) NSURL * localURL;
@property long long garbageCollectionBehavior;
@property(copy) id progressHandler;
@property(retain) NSDictionary * downloadOptions;


- (bool)requiredDiskSpaceIsAvailable:(long long*)arg1 error:(id*)arg2;
- (void)adjustDownloadOptions:(id)arg1 completion:(id)arg2;
- (void)cancelDownload:(id)arg1;
- (void)purge:(id)arg1;
- (id)assetType;
- (bool)cancelDownloadAndReturnError:(id*)arg1;
- (id)downloadOptions;
- (long long)garbageCollectionBehavior;
- (bool)resumeDownloadAndReturnError:(id*)arg1;
- (bool)pauseDownloadAndReturnError:(id*)arg1;
- (void)_downloadWithOptions:(id)arg1 shouldFireCallback:(bool)arg2;
- (void)setDownloadOptions:(id)arg1;
- (bool)requiredDiskSpaceIsAvailableForDownloadOptions:(id)arg1 requiredBytes:(long long*)arg2 error:(id*)arg3;
- (struct __MobileAsset { struct __CFRuntimeBase { unsigned long long x_1_1_1; unsigned char x_1_1_2[4]; unsigned int x_1_1_3; } x1; struct __CFString {} *x2; struct __CFDictionary {} *x3; struct __MobileAssetQuery {} *x4; struct __MobileAssetQuery {} *x5; unsigned char x6; }*)mobileAsset;
- (long long)assetStateForStateString:(id)arg1;
- (id)_getLocalAttribute:(id)arg1;
- (void)setProgressHandler:(id)arg1;
- (bool)purgeAndReturnError:(id*)arg1;
- (void)beginDownloadWithOptions:(id)arg1;
- (id)localURL;
- (id)attributes;
- (long long)state;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)progressHandler;
- (void)setGarbageCollectionBehavior:(long long)arg1;
- (void)pauseDownload:(id)arg1;
- (void)resumeDownload:(id)arg1;
- (bool)isPresentOnDisk;
- (id)fullAttributes;
- (id)initWithAssetType:(id)arg1 attributes:(id)arg2;
- (void)setClientName:(id)arg1;
- (id)clientName;
- (id)identifier;
- (long long)_contentVersion;
- (long long)_formatVersion;

@end
