/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVAssetWriterInputPassDescriptionInternal, NSArray;

@interface AVAssetWriterInputPassDescription : NSObject  {
    AVAssetWriterInputPassDescriptionInternal *_internal;
}

@property(readonly) NSArray * sourceTimeRanges;


- (void)finalize;
- (id)description;
- (id)init;
- (void)dealloc;
- (id)sourceTimeRanges;
- (id)initWithTimeRanges:(id)arg1;

@end
