/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSURL, AVAssetCacheInternal;

@interface AVAssetCache : NSObject  {
    AVAssetCacheInternal *_priv;
}

@property long long maxSize;
@property long long maxEntrySize;
@property(readonly) long long currentSize;
@property(copy,readonly) NSURL * URL;

+ (id)assetCacheWithURL:(id)arg1;

- (void)finalize;
- (void)setMaxEntrySize:(long long)arg1;
- (id)URL;
- (id)initWithURL:(id)arg1;
- (void)setMaxSize:(long long)arg1;
- (long long)maxSize;
- (void)dealloc;
- (id)allKeys;
- (id)lastModifiedDateOfEntryForKey:(id)arg1;
- (long long)sizeOfEntryForKey:(id)arg1;
- (void)removeEntryForKey:(id)arg1;
- (long long)currentSize;
- (long long)maxEntrySize;

@end
