/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVAssetWriterHelper, AVWeakReference, NSObject<OS_dispatch_queue>;

@interface AVAssetWriterInternal : NSObject  {
    AVWeakReference *weakReference;
    AVAssetWriterHelper *helper;
    NSObject<OS_dispatch_queue> *helperReadWriteQueue;
}



@end
