/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSString, NSDate;

@interface AVAssetResourceLoadingContentInformationRequestInternal : NSObject  {
    NSString *contentType;
    long long contentLength;
    boolbyteRangeAccessSupported;
    NSDate *renewalDate;
    booldiskCachingPermitted;
}



@end
