/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVAssetWriterInputPassDescriptionResponder, AVWeakReference, AVAssetWriterInputHelper, NSObject<OS_dispatch_queue>;

@interface AVAssetWriterInputInternal : NSObject  {
    AVWeakReference *weakReference;
    AVAssetWriterInputHelper *helper;
    NSObject<OS_dispatch_queue> *helperQueue;
    boolattachedToPixelBufferAdaptor;
    boolattachedToMetadataAdaptor;
    AVWeakReference *weakReferenceToAssetWriter;
    long long numberOfAppendFailures;
    NSObject<OS_dispatch_queue> *appendFailureReadWriteQueue;
    AVAssetWriterInputPassDescriptionResponder *passDescriptionResponder;
}



@end
