/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@class NSString;

@interface AVAudioSessionChannelDescription : NSObject  {
    void *_impl;
}

@property(readonly) NSString * channelName;
@property(readonly) NSString * owningPortUID;
@property(readonly) unsigned long long channelNumber;
@property(readonly) unsigned int channelLabel;

+ (id)privateCreateArray:(id)arg1 portUID:(id)arg2;
+ (id)privateCreate:(id)arg1 portUID:(id)arg2 channelNumber:(unsigned int)arg3;

- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;
- (unsigned int)channelLabel;
- (id)channelName;
- (bool)isEqualToChannel:(id)arg1;
- (struct ChannelDescriptionImpl { id x1; id x2; unsigned int x3; unsigned int x4; }*)privateGetImplementation;
- (unsigned long long)channelNumber;
- (id)owningPortUID;

@end
