/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, AVWeakReference, AVWeakKeyValueObserverProxy, AVCaptureDevice;

@interface AVCaptureDeviceInputInternal : NSObject  {
    AVCaptureDevice *device;
    NSArray *ports;
    boolready;
    boolauthorizedForCamera;
    AVWeakReference *weakReference;
    AVWeakKeyValueObserverProxy *KVOProxy;
}


- (void)dealloc;

@end
