/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSString, AVCaptureInput_FigRecorder;

@interface AVCaptureInputPortInternal_FigRecorder : NSObject  {
    AVCaptureInput_FigRecorder *input;
    NSString *mediaType;
    struct opaqueCMFormatDescription { } *formatDescription;
    struct OpaqueCMClock { } *clock;
    boolenabled;
}


- (id)init;
- (void)dealloc;

@end
