/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class <AVExternalDeviceDelegate>, AVWeakReference, NSArray;

@interface AVExternalDeviceInternal : NSObject  {
    struct OpaqueFigEndpoint { } *_figEndpoint;
    <AVExternalDeviceDelegate> *_delegate;
    AVWeakReference *_weakReference;
    NSArray *_HIDs;
    long long _makeHIDsOnlyOnce;
}



@end
