/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVExternalDeviceHIDInternal, NSString;

@interface AVExternalDeviceHID : NSObject  {
    AVExternalDeviceHIDInternal *_externalDeviceHID;
}

@property(readonly) NSString * UUID;
@property(readonly) NSString * screenID;
@property long long inputMode;


- (void)finalize;
- (void)setInputMode:(long long)arg1;
- (id)UUID;
- (void)dealloc;
- (long long)inputMode;
- (id)initWithExternalDeviceAndHIDDictionary:(id)arg1 hidDictionary:(id)arg2;
- (id)_figEndpointHIDInputMode;
- (id)_externalDevice;
- (id)screenID;

@end
