/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVExternalDevice;

@interface AVExternalDeviceTurnByTurnToken : NSObject  {
    AVExternalDevice *_externalDevice;
}


- (void)finalize;
- (id)init;
- (void)dealloc;
- (id)initWithExternalDevice:(id)arg1;

@end
