/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVWeakReference;

@interface AVFlashlightInternal_FigRecorder : NSObject  {
    struct OpaqueFigRecorder { } *recorder;
    AVWeakReference *weakReference;
    booloverheated;
    boolavailable;
    float flashlightLevel;
}



@end
