/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVMetadataMachineReadableCodeObjectInternal, NSArray, NSString;

@interface AVMetadataMachineReadableCodeObject : AVMetadataObject  {
    AVMetadataMachineReadableCodeObjectInternal *_internal;
}

@property(readonly) NSArray * corners;
@property(readonly) NSString * stringValue;

+ (id)machineReadableCodeObjectWithFigEmbeddedCaptureDeviceMachineReadableCodeDictionary:(id)arg1 input:(id)arg2;

- (id)stringValue;
- (id)corners;
- (id)description;
- (void)dealloc;
- (id)initWithFigEmbeddedCaptureDeviceMachineReadableCodeDictionary:(id)arg1 input:(id)arg2;
- (id)initDerivedMetadataObjectFromMetadataObject:(id)arg1 withTransform:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg2 isVideoMirrored:(bool)arg3 rollAdjustment:(double)arg4;

@end
