/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSMutableArray;

@interface AVRunLoopCondition : NSCondition  {
    NSMutableArray *_runLoopStateList;
}


- (void)wait;
- (void)broadcast;
- (bool)waitUntilDate:(id)arg1;
- (void)signal;
- (id)init;
- (void)dealloc;
- (void)_signalRunLoopWithState:(id)arg1;
- (bool)_waitInMode:(id)arg1 untilDate:(id)arg2;
- (bool)waitUntilDate:(id)arg1 inMode:(id)arg2;
- (void)waitInMode:(id)arg1;

@end
