/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSObject<OS_dispatch_queue>, AVPlayerItem;

@interface AVSynchronizedLayerInternal : NSObject  {
    AVPlayerItem *playerItem;
    boolisVisible;
    NSObject<OS_dispatch_queue> *serialQueue;
}



@end
