/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, AVVideoCompositionInstructionInternal, NSString;

@interface AVVideoCompositionInstruction : NSObject <NSSecureCoding, NSCopying, NSMutableCopying, AVVideoCompositionInstruction> {
    AVVideoCompositionInstructionInternal *_instruction;
}

@property(readonly) struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; } timeRange;
@property(retain) struct CGColor { }* backgroundColor;
@property(copy,readonly) NSArray * layerInstructions;
@property(readonly) bool enablePostProcessing;
@property(readonly) NSArray * requiredSourceTrackIDs;
@property(readonly) int passthroughTrackID;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) bool containsTweening;

+ (void)initialize;
+ (bool)supportsSecureCoding;

- (void)finalize;
- (void)setTimeRange:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg1;
- (struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })timeRange;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (bool)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (struct CGColor { }*)backgroundColor;
- (id)initWithCoder:(id)arg1;
- (void)setBackgroundColor:(struct CGColor { }*)arg1;
- (void)dealloc;
- (int)passthroughTrackID;
- (id)requiredSourceTrackIDs;
- (bool)containsTweening;
- (void)setLayerInstructions:(id)arg1;
- (void)_setValuesFromDictionary:(id)arg1;
- (void)setEnablePostProcessing:(bool)arg1;
- (bool)enablePostProcessing;
- (id)layerInstructions;

@end
