/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVVideoPerformanceMetricsInternal;

@interface AVVideoPerformanceMetrics : NSObject  {
    AVVideoPerformanceMetricsInternal *_performanceMetricsInternal;
}

@property(readonly) unsigned long long totalNumberOfVideoFrames;
@property(readonly) unsigned long long numberOfDroppedVideoFrames;
@property(readonly) unsigned long long numberOfCorruptedVideoFrames;
@property(readonly) double totalFrameDelay;


- (void)finalize;
- (id)initWithDictionary:(id)arg1;
- (id)init;
- (void)dealloc;
- (unsigned long long)numberOfDroppedVideoFrames;
- (double)totalFrameDelay;
- (unsigned long long)numberOfCorruptedVideoFrames;
- (unsigned long long)totalNumberOfVideoFrames;

@end
