/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSDictionary;

@interface AVVideoOutputSettings : AVOutputSettings  {
}

@property(readonly) int width;
@property(readonly) int height;
@property(readonly) NSDictionary * cleanApertureDictionary;
@property(readonly) NSDictionary * pixelAspectRatioDictionary;
@property(readonly) NSDictionary * pixelTransferProperties;
@property(readonly) NSDictionary * videoScalingProperties;
@property(readonly) NSDictionary * videoCompositionProcessorProperties;
@property(readonly) bool dimensionsAreBoundingBox;
@property(readonly) NSDictionary * videoSettingsDictionary;

+ (id)videoOutputSettingsWithTrustedVideoSettingsDictionary:(id)arg1;
+ (id)_validValuesForScalingMode;
+ (id)defaultVideoOutputSettings;
+ (id)registeredOutputSettingsClasses;
+ (id)videoOutputSettingsWithVideoSettingsDictionary:(id)arg1;
+ (id)_videoOutputSettingsWithVideoSettingsDictionary:(id)arg1 exceptionReason:(id*)arg2;
+ (id)_outputSettingsWithOutputSettingsDictionary:(id)arg1 exceptionReason:(id*)arg2;

- (int)height;
- (int)width;
- (bool)dimensionsAreBoundingBox;
- (id)cleanApertureDictionary;
- (id)pixelAspectRatioDictionary;
- (id)initWithVideoSettingsDictionary:(id)arg1 exceptionReason:(id*)arg2;
- (bool)validateUsingOutputSettingsValidator:(id)arg1 reason:(id*)arg2;
- (id)videoCompositionProcessorProperties;
- (id)videoSettingsDictionary;
- (id)videoScalingProperties;
- (id)pixelTransferProperties;
- (id)compatibleMediaTypes;

@end
